### ISSUE TITLE
Добавить возможность ограничения количества выбранных  ресурсов в дереве

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#1]

**Comment by yellow-sky** [comment]
По умолчанию поставить 20 элементов

**Comment by karavanjo** [comment]
Предлагаю внести изменения в логику валидатора. Речь должна идти не о количестве выделенных ресурсов в дереве, а в количестве слоев на карте. Следовательно надо отслеживать кол-во выбранных ресурсов, умноженное на количество выбранных слоев. Иначе получится ситуация, когда 20 ресурсов с 1 типом слоя дают 20 слоев и 20 с 10 типами дают 200 слоев - совершенно разные цифры.
