### ISSUE TITLE
Перенести контрол изменения статуса в меню

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#109]
Поле «Статус строительства» занимает слишком много места на форме, хотя по факту изменять статус будут один единственный раз в конце строительства (если вообще будут). Статус строительства «Идет строительство» у нас устанавливается автоматически, а статус «Построено» мне кажется должен устанавливать руководитель проекта по результатам выездной проверки. Поэтому предлагаю поле «Статус строительства» убрать с формы, но возможность изменения статуса из мобильного приложения оставить. Для этого добавить в меню пункт «Изменить статус линии связи». Этот пункт меню должен быть доступен только с формы выбора Вида работ.
![image](https://cloud.githubusercontent.com/assets/1277422/8615066/38584bb4-26f8-11e5-9a19-a8f5f831df3e.png)

**Comment by NikitaFeodonit** [comment]
Повтор #116. Этот закрываю.
