### ISSUE TITLE
Закрытие формы ввода очень длительная

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#113]
Очень долго закрывается форма ввода данных после нажатия кнопки Готово. Форма закрывается 5-10 сек.

**Comment by yellow-sky** [comment]
У меня 2-3 секунды. Почему у него так долго, я не могу понять. Возможно, что-то с файловой системой у него. Но я думаю это время зависит от количества фотографий.
Может мы ему какую то программу отправим, которая проверит скорость записи на его диск?

**Comment by NikitaFeodonit** [comment]
Скорее всего действительно проблемы с файловой системой. Всё, что смог сделать, это уменьшить время записи фото на 14% (тикет "ngm_clink_monitoring #165").
