### ISSUE TITLE
Поменять местами наименование района и области в списке линий

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#115]
На форме выбора линии связи, у некоторых линий связи не отображается наименование района. Как вариант можно попробовать уменьшить размер или тип шрифта. Кроме того предлагаю сначала отображать наименование района, а затем область. Например, Александровский р-н, Владимирская обл.

**Comment by NikitaFeodonit** [comment]
Как вариант делать в три строки:
Название линии
название области
название района

**Comment by NikitaFeodonit** [comment]
Пока сделал вариант в три строки, так можно вписать любые названия облаестей и районов. И слова "обл." и "р." можно полными сделать.
