### ISSUE TITLE
Странности с фото 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#118]
1) На вкладке Файлы у одной из точек прокладки кабеля отображается какая-то левая фотография, которую я снимал не вчера в полях, а накануне вечером в электричке, когда данные по Владимирской области еще не были загружены на сервер. Почему она отображается на карточке этого объекта?
![image](https://cloud.githubusercontent.com/assets/1277422/8624459/b19e0cf0-2740-11e5-8fc2-b66e70499ebd.png)
2) У одной из точек на сервере не отображаются фотографии, хотя я их точно делал. На фотографиях должно быть изображена яма, в которую уложены запасы кабеля (это место установки муфты). Когда я фиксировал эту точку у меня мобильное приложение несколько раз аварийно завершало работу.
![image](https://cloud.githubusercontent.com/assets/1277422/8624471/c2a2725c-2740-11e5-8c91-2cdc6f655b97.png)

**Comment by yellow-sky** [comment]
Я попросил копия дирректории с его мобильного, может поможет:
https://drive.google.com/open?id=0B8fD-l_uK4vFNGxjZDAxci1CeDVmX0tONjlHR2ZTeUtzT21N

**Comment by NikitaFeodonit** [comment]
Перенес к себе, тут закрываю.
