### ISSUE TITLE
Организация меню

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#128]
Пункт меню Выход предлагаю разместить в выпадающем подменю, которое должно открываться по щелчку на ФИО текущего пользователя (см. скриншот ниже).

**Comment by drnextgis** [comment]
Выпадающее меню показывать только для аутентифицированных пользователей, а для гостя никакого выпадающего меню, просто ссылка на форму входа? Это относится к данному проекту или это имеет смысл сделать в самом ngw?

**Comment by yellow-sky** [comment]
К нгв не относится. Относится только к шаблонам в колинке.
В колинке не может быть неавторизованных пользователей. Поэтому меню
показывать всегда

18 сентября 2015 г., 10:32 пользователь Denis Rykov <
notifications@github.com> написал:

> Выпадающее меню показывать только для аутентифицированных пользователей, а
> для гостя никакого выпадающего меню, просто ссылка на форму входа? Это
> относится к данному проекту или это имеет смысл сделать в самом ngw?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/nextgisweb_compulink/issues/128#issuecomment-141370297>
> .
>



-- 

Best regards,

Nikulin Eugeny
