### ISSUE TITLE
Съехала основная форма

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#130]
Контейнер с картой ушел вниз на размер панели, которую добавил в шаблоне.
Попытка исправить в https://github.com/nextgis/nextgisweb_compulink/commit/1222b2cd0e68d5f7ef78d80f631e0d84e066b67e привело к какой-то неадекватности контейнеров dojo

**Comment by karavanjo** [comment]
Функционал заголовка выделен в отдельный виджет, конфигируемый глобальной переменной. При первичной инициализации - все хорошо.

![image](https://cloud.githubusercontent.com/assets/669999/9269992/d1bc93d4-4276-11e5-913d-f5907c7d7c91.png)

Но при ресайзе окна - возникают проблемы.

**Comment by yellow-sky** [comment]
![image](https://cloud.githubusercontent.com/assets/1277422/9626725/3ea32a30-5168-11e5-993d-54612a634177.png)
Не работает вертикаль и горизонталь.

**Comment by yellow-sky** [comment]
Работает
