### ISSUE TITLE
Легенда. Генерация картинки по файлу стиля силами mapserver

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#136]
Нужно договориться куда писать название класса и куда писать тип геометрии

**Comment by drnextgis** [comment]
Тип геометрии описывается внутри `layer`, доступные типы: `line`, `point`, `polygon`. Пример:

```
<layer>
    <type>point</type>
    ...
</layer>
```

Название класса можно указать внутри `class`. Пример:

```
<class>
    <name>Воздушные линии связи</name>
    ...
</class>
```
