### ISSUE TITLE
Добавить возможность указания отмеченных типов слоев по умолчанию

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#14]

**Comment by karavanjo** [comment]
Реализовано путем добавления списка selectedByDefault в настройки конструктора.

![image](https://cloud.githubusercontent.com/assets/669999/5911108/ee4a2c3c-a5d2-11e4-8b6d-61bfe4be17e3.png)

**Comment by yellow-sky** [comment]
Работает
