### ISSUE TITLE
Фронтенд для системы отчетов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#140]
Фронтенд для отчетов - отдельная страница в веб интерфейсе, на которой в верхней части идет строка с фильтрами:

1) Субъект РФ (заполнение должно осуществляться путем выбора из выпадающего списка)
2) Муниципальный район (заполнение должно осуществляться путем выбора из выпадающего списка, перечень элементов в списке должен зависеть от значения, указанного в параметре «Субъект РФ»)
3) Статус строительства (должна быть возможность выбрать один или несколько статусов)
4) Показывать только просроченные (чекбокс)

а остальная часть заполняется результатами отработки бэкенда:

таблица представленная заказчиком.

Примечание: Просроченные линии должны отображаться шрифтом красного цвета в том случае, если статус проекта не равен «Построено» или «Принято заказчиком».

**Comment by yellow-sky** [comment]
Предлагаю в меню создать новый пункт Отчеты, по нажатию на который будет открываться выпадающее меню, в котором будет отображаться пока единственный пункт «Отчет о ходе строительства».

**Comment by yellow-sky** [comment]
Первый фидбек:
1) значения в столбцах начиная с "Плановые сроки выполнения СМР" должны выравниваться по гризонтали
2) в отчете в вебе внизу таблицы должны выводиться итоговые данные
3) надпись "Регион" переименовать в "Район"
4)  в параметрах отчета в списке районов и регионов показывать только те районы, по которым есть объекты строительства в системе (тут нужно доделывать мне наверное)
5)  Переименовать "Просроченные" в "Только просроченные"
6) в параметрах отчета в списке Регионов добавить пункт Все. При его выборе не отправлять фильтры по территориям. районы заблокировать
7) в параметрах отчета в списке Районов добавить пункт Все. При его выборе не отправлять фильтры по районам

**Comment by yellow-sky** [comment]
Добавить кнопку "Выгрузить в Excel".
Ссылка - /compulink/reporting/export_status_report 
Параметры такие же как и для сервиса генерации репортов.

Ссылку лучше открывать в новой вкладке, что бы текущую страницу не перезагрузать.

**Comment by yellow-sky** [comment]
в поле выбора статусов нужно добавить возможность выбора всех статусов. по умолчанию должны быть выбраны все статусы. статусы в выпадающем списке нужно расположить в хронологическом порядке: Строительство не начато, Идет строительство, Построено, Сдано заказчику

**Comment by drnextgis** [comment]
Рано закрыл, у нас еще не реализовано меню в том виде, что они просят.
