### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb_compulink#15]
1. УЦН - Курская область - Мантуровский район, отмечаем;
2. Сверху слева в выпадающем списке выбираем Ситуационные планы;
3. Получаем ошибку в консоли:

   ```
   Uncaught TypeError: Cannot read property 'indexOf' of undefined
   ```

**Comment by yellow-sky** [comment]
Невоспроизводится
