### ISSUE TITLE
Не работает идентификация после внедрения нового механизма рендеринга

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#165]

**Comment by karavanjo** [comment]
Реализована поддержка многослойного рендеринга при идентификации.

![image](https://cloud.githubusercontent.com/assets/669999/9871253/0763b96c-5b9b-11e5-99dc-f21b86be5f0e.png)

Готово к тестированию.

**Comment by yellow-sky** [comment]
Проверил
