### ISSUE TITLE
Заменить картинку чекбокса на более строгую

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#17]
![unnamed](https://cloud.githubusercontent.com/assets/1277422/5934706/06ccae6c-a6e4-11e4-8709-9a347cd0231d.png)

**Comment by yellow-sky** [comment]
Можно ли поменять темой или просто подложив картинки чеков?

**Comment by karavanjo** [comment]
Можно, поменяю.

**Comment by karavanjo** [comment]
Вариант заккомитан:
![image](https://cloud.githubusercontent.com/assets/669999/6110741/de76ba7e-b094-11e4-8eb4-0d3100d26790.png)

Если устраивает можно закрывать.

**Comment by yellow-sky** [comment]
Пока так оставляем. я думаю заказчику понравится
