### ISSUE TITLE
Индикация загрузки слоев карт

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#171]
Необходимо вставить стандартный индикатор загрузки слоев OL.
Сейчас неясно, когда данные загрузились, а когда нужно ждать.

**Comment by karavanjo** [comment]
Как в этом примере - http://openlayers.org/en/v3.9.0/examples/tile-load-events.html?

**Comment by yellow-sky** [comment]
оо ) прикольно. было бы классно наверное. Но это же 3ка. а у нас 2ка?

2015-09-17 17:01 GMT+03:00 karavanjo <notifications@github.com>:

> Как в этом примере -
> http://openlayers.org/en/v3.9.0/examples/tile-load-events.html?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/nextgisweb_compulink/issues/171#issuecomment-141095827>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by karavanjo** [comment]
Да. Я подумаю над решением. А какое стандартное для 2 версии OpenLayers?

**Comment by yellow-sky** [comment]
там вроде кружок крутился сверху справа? или я путаю с чем то?

17 сентября 2015 г., 17:04 пользователь karavanjo <notifications@github.com>
написал:

> Да. Я подумаю над решением. А какое стандартное для 2 версии OpenLayers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/nextgisweb_compulink/issues/171#issuecomment-141096459>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by karavanjo** [comment]
Индикация загрузки должна реагировать на загрузку тайлов базового слоя (подложки)?

**Comment by yellow-sky** [comment]
да. давай для всей карты делать

6 октября 2015 г., 14:51 пользователь Ivan Kavaliou <
notifications@github.com> написал:

> Индикация загрузки должна реагировать на загрузку тайлов базового слоя
> (подложки)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/nextgisweb_compulink/issues/171#issuecomment-145834707>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by karavanjo** [comment]
Реализовано, но в текущем варианте пока только для слоев данных:

![layers-loading](https://cloud.githubusercontent.com/assets/669999/10417573/898d52be-7049-11e5-8b01-883083853824.gif)

Базовые слои добавлю. Пока можно потестировать со слоями данных.

**Comment by karavanjo** [comment]
Добавил поддержку базовых слоев. Но сейчас на карту добавлено несколько базовых слоев, точнее 7. Поэтому загрузка одного базового слоя отражается только одним делением.
![blayers-loading](https://cloud.githubusercontent.com/assets/669999/10417701/14033220-704e-11e5-813f-7a43067d280b.gif)
