### ISSUE TITLE
Изменения в меню главного окна

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#172]
В выпадающем меню главного окна необходимо внести изменения.
В случае,когда у пользователя есть административные права (is_administrtor) необходимо выводить два пункта:
Управление ресурсами (ссылка на /resource/0)
Панель управления (ссылка на /control-panel)

Ниже этих кнопок должна быть кнопка Выход.

**Comment by drnextgis** [comment]
Чем это отличается от #128? Почему ссылка на ресурсы только для администратора, ресурсы ведь может просматривать любой пользователь, или это условие показывать пункт с ресурсами чисто для данного проекта, а в ядре можно показывать ссылку на ресурсы всем?

**Comment by yellow-sky** [comment]
Нет, эти пункту нужны будут только админам. простым пользователям - нет. И
для пользователей будем закрывать нгвшный интерфейс.
Отличиается тем, что раньше был один пункт - Панель управления, теперь два
- ПУ и Ресурсу.

18 сентября 2015 г., 10:36 пользователь Denis Rykov <
notifications@github.com> написал:

> Чем это отличается от #128
> <https://github.com/nextgis/nextgisweb_compulink/issues/128>? Почему
> ссылка на ресурсы только для администратора, ресурсы ведь может
> просматривать любой пользователь, или это условие показывать пункт с
> ресурсами чисто для данного проекта, а в ядре можно показывать ссылку на
> ресурсы всем?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/nextgisweb_compulink/issues/172#issuecomment-141371038>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by yellow-sky** [comment]
Откатились до версии, что под Пользователем должен быть только один пункт - Выход.
Все остальные пункты вернуть в строку, пункт Отчеты тоже сделать выпадающим.
