### ISSUE TITLE
Диалог изменения статуса объекта строительства

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#175]
В панели внизу есть объекты строительства. 
По правому клику есть выпадающее меню.
В него необходимо добавить новый пункт (после разделителя) "Изменить статус". 
При вызове данного пункта должен появляться диалог изменения статуса. 
Диалог аналогичен тому, который появляется при превышении кол-ва слоев. 
Заголовок - "Изменение статуса объекта строительства"
Кнопки - Сохранить Отменить. 
На самой форме должен быть выпадающий комбо-бокс со статусами (список известен). Начальное значение должно соответствовать текущему статусу.
При установке статуса должна быть обязательная проверка прав.

**Comment by yellow-sky** [comment]
Бэкенд с методами я сделаю. Иван, если есть желание, можешь сделать форму )

**Comment by yellow-sky** [comment]
Сделал серверную часть:
URL вида: /compulink/resources/{id:\d+}/focl_status возвращает статус проекта и все возможные статусы.
URL вида: /compulink/resources/{id:\d+}/set_focl_status?status=new_status устанавливает новый.

**Comment by karavanjo** [comment]
Дизайн окон с результатом операции изменения статуса выполнен в стиле темы *claro*:
![image](https://cloud.githubusercontent.com/assets/669999/10305877/bd26d84c-6c2b-11e5-8c47-c6638f5d067e.png)
