### ISSUE TITLE
В панели с типами слоев добавить изображения легенды

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#18]
Напротив каждого слоя добавить картинку с условным отображением

**Comment by yellow-sky** [comment]
Картинки будут готовы позже.
сейчас можно предусмотреть сам механизм добавления. Например вызов картинки по какому то урлу, с передачей типа слоя.

**Comment by karavanjo** [comment]
Механизм добавления иконок на фронтенде предусмотрен. Хранением иконок будет управлять NGW Admin? Или это будет фиксированный статический набор, который будет назначаться с помощью css?

**Comment by yellow-sky** [comment]
Я предлагаю css'ом. В админки это делать накладно.

**Comment by karavanjo** [comment]
Тогда, пока нет картинок - я нагенерю тестовые иконки с разными цветами и строгим стилем. Например:
![colors](https://cloud.githubusercontent.com/assets/669999/6437859/a0cef718-c0d4-11e4-91c1-adce63a6afec.jpg)

Только заливку еще добавлю.

**Comment by yellow-sky** [comment]
Да, нормально.
Но название иконок желательно должно называться в соответствии с типом слоев.

**Comment by karavanjo** [comment]
Добавлен тестовый вариант иконок:

![image](https://cloud.githubusercontent.com/assets/669999/6555836/0d9cdc48-c67a-11e4-937f-e7c41a0ff938.png)

**Comment by yellow-sky** [comment]
Работает
