### ISSUE TITLE
Выровнять sub-menu пользователя по правому краю

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#188]
![image](https://cloud.githubusercontent.com/assets/669999/10226540/aa87acca-6870-11e5-832a-6e01baba4db5.png)

**Comment by drnextgis** [comment]
Иван, а можно сделать, чтобы выпадающее меню правым своим краем совпадало с правым краем родителя, а ширина формировалась по содержимому, но не меньше чем ширина родителя. А то, например, если имя пользователя слишком короткое, а в выпадающее меню добавить длинное название, то его будет не видно.

**Comment by karavanjo** [comment]
Да, я так и хотел сделать. Но быстрого и простого решения не нашел. Пока хватает critical issues поэтому предлагаю оставит так. Останется время или возникнет необходимость - сделаем. Пока даже для имени пользователя с одной буквой существующие пункты меню отобразятся нормально.

**Comment by drnextgis** [comment]
Просто если обновишься, там добавился слева выпадающий пункт Отчёты и в нём длинное название отчёта, а ширина как у родителя, можно хотя бы без прилипания к правой стороне поправить ширину меню?

**Comment by karavanjo** [comment]
Зада понятна. Подумаю над решением.

**Comment by karavanjo** [comment]
Выделено в https://github.com/nextgis/nextgisweb_compulink/issues/193
