### ISSUE TITLE
Добавить полосы прокрутки в диспетчер типов слоев

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#189]
![image](https://cloud.githubusercontent.com/assets/669999/10242604/ab0fc300-68fa-11e5-8ab1-a4f34ed17ebf.png)

**Comment by karavanjo** [comment]
Изменен механизм смены режимов отображения панелей - в старой версии использовались стили CSS в зависимости от установленного атрибута `data-resource-type-filter` в значениях `vols` и `vols`. В новой версии механизм рендеринга панелей типов слоев и легенды осуществляется динамически, путем очистки `BorderContainer` и заполнения его панелями, которые инициализируются при загрузке страницы [здесь](https://github.com/nextgis/nextgisweb_compulink/blob/270119d6dc5956471bf80fe08c78e83c011dbdbf/nextgisweb_compulink/compulink_site/amd/ngw-compulink-site/templates/Display.html#L230). Настройки отображения панелей расположены [здесь](https://github.com/nextgis/nextgisweb_compulink/blob/270119d6dc5956471bf80fe08c78e83c011dbdbf/nextgisweb_compulink/compulink_site/amd/ngw-compulink-site/LayersSelector.js#L173).

**Comment by yellow-sky** [comment]
Работает
