### ISSUE TITLE
Релизовать компонент меню для заголовка страницы

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#193]
Требования:
1. Выравнивание дочерних элементов по правому краю границы родителя.
2. Адаптивная ширина элемента меню под текст надписи.

**Comment by drnextgis** [comment]
Потестил, вот чего не хватает:

1. Пропал треугольник, который был возле заголовка меню
2. Пропала подсветка выделенных элементов (hover)
3. Если можно - задать минимальную ширину меню, равную имени заголовка.

**Comment by drnextgis** [comment]
4. В Firefox всё съехало.

**Comment by yellow-sky** [comment]
работает
