### ISSUE TITLE
Уменьшить высоту индикатора загрузки данных

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#207]

**Comment by karavanjo** [comment]
Варианты:
Текущий, 12px
![image](https://cloud.githubusercontent.com/assets/669999/10522901/4806b576-7380-11e5-8b4a-dc59ec0f1879.png)

10px
![image](https://cloud.githubusercontent.com/assets/669999/10522910/5ab1d818-7380-11e5-9fa5-d7cf10b2d48b.png)

8px
![image](https://cloud.githubusercontent.com/assets/669999/10522922/6cea0ffa-7380-11e5-87e7-555176cb283f.png)

6px
![image](https://cloud.githubusercontent.com/assets/669999/10522936/7ccd7b0a-7380-11e5-9afa-496847adfd8a.png)

**Comment by simgislab** [comment]
6px

**Comment by yellow-sky** [comment]
да, 6той
