### ISSUE TITLE
Отчеты в веб: 3 знака после запятой 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#211]
В итоговой строке, в поле Прокладка Факт КМ получается число (неясно как?) число с большим количеством знаков после запятой и появляется троеточие:

https://gis.compulink.ru/compulink/reporting/grid
![image](https://cloud.githubusercontent.com/assets/1277422/10636128/161ffef2-7806-11e5-9fe3-2fadc1868853.png)

Во всех полях (дробных) не должно быть больше 3х знаков после запятой.

**Comment by drnextgis** [comment]
Как мне у себя воспроизвести такую ситуацию, чтобы проверить?

**Comment by drnextgis** [comment]
Вроде поравил в https://github.com/nextgis/nextgisweb_compulink/commit/ed6d888e3ac54f53d3106cf3c5c26d81c4d7341d
