### ISSUE TITLE
Реализовать вызов редактора из контекстного меню таблицы объектов строительства

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#216]
Добавить пункт меню "Редактировать"
![image](https://cloud.githubusercontent.com/assets/669999/10725614/7349f200-7bde-11e5-8d0f-510506f4a992.png)
При клике должна открываться страница редактора с GET параметром resource_id.

**Comment by yellow-sky** [comment]
Редактор должен вызываться в новой вкладке. Текущая вкладка должна остаться неизменной
