### ISSUE TITLE
Веб-отчеты: не полностью отображается наименование подрядчика

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#217]
![image](https://cloud.githubusercontent.com/assets/1277422/10970067/440fe5ba-83dd-11e5-9576-23f8f6de95e1.png)

**Comment by drnextgis** [comment]
https://github.com/nextgis/nextgisweb/commit/a7033b1cc863db4d9ed01be7a09a91c2272f1bc3 и https://github.com/nextgis/nextgisweb_compulink/commit/fda55bf85ab64ad03a2f7741fea28ad4b5c642b6 должны исправить ситуацию
