### ISSUE TITLE
Вернуть чек-боксы на все уровни дерева ВОЛС\СитПланов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#23]
Так как в данный момент появилась возможность ограничивать кол-во включенных слоев, необходимо вернуть галки на все уровни дерева.

**Comment by karavanjo** [comment]
Возникла проблема с этим требованием.

Дерево сейчас загружается с отложенной загрузкой узлов. Ограничитель вывода - окно с лимитом выбора количества слоев - требует рассчитать кол-во узлов дерева нижнего уровня, которые пользователь сможет выбрать. Для верхнего уровня мы получим такой сценарий -
1. Пользователь выбирает УЦН
![image](https://cloud.githubusercontent.com/assets/669999/6605152/ac5b6ed8-c83e-11e4-9d2c-be192faf55f4.png)
2. LimitLayersValidator вынужден будет опросить рекурсивно все вложенные узлы, чтобы оценить кол-во выбранных пользователем узлов.
3. При большом дереве получим проблему.

Учитывая, что требование возникло в связи с тем, что пользователю не видно, какие галки выбран в дочерних ветках, т.е. необходимо чтобы отображались чекбоксы со статусом "внутри выбраны не все галки" предлагаю следующее решение - отображать галки на всех уровнях с отображением состояния, но запретить отмечать чекбоксы, которые находятся выше группы ресурсов. Иначе говоря - так как работает сейчас, только с отображение чекбоксов и их состояний.

**Comment by karavanjo** [comment]
Отображение чекбоксов включено, но запрещено выделение на узлах выше первой группы ресурсов:
![image](https://cloud.githubusercontent.com/assets/669999/6614369/5ff07ea0-c8aa-11e4-8fc0-1330e19b7aeb.png)

Если реализации устроит - можно закрывать после тестирования.
