### ISSUE TITLE
Не отображаются слои при свернутой правой панели

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#240]
Если свернуть панель справа, то вновь добавленные слои перестают отображаться

**Comment by karavanjo** [comment]
Исправлено.
![240](https://cloud.githubusercontent.com/assets/669999/16266723/f5d357ee-388e-11e6-8c2c-b87d4270c4be.gif)

**Comment by yellow-sky** [comment]
Работает
