### ISSUE TITLE
В списке найденных объектов окна идентификации выводить поле Name и название родительского ресурса

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#25]
В случае, если поля Name нет, либо оно пустое выводить как и прежде #объекта
Например:
РМ-01 (ВОЛС Илловайск)
 # 1 (ВОЛС Дебальцово)

**Comment by drnextgis** [comment]
Поле, которое нужно выводить при идентификации, можно указать в настройках векторного слоя во вкладке *Атрибуты*, отметив соответствующее поле чекбоксом *АН*. Этой возможности недостаточно?
