### ISSUE TITLE
Необходимо добавить легенду на графики

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#250]
![image](https://cloud.githubusercontent.com/assets/1277422/11749659/27150d58-a040-11e5-986f-8f9d3f3a502f.png)

**Comment by karavanjo** [comment]
Легенды к диаграммам добавлена, пример:
![image](https://cloud.githubusercontent.com/assets/669999/11767782/51370448-a1ca-11e5-88ea-ecc396832b6d.png)

**Comment by yellow-sky** [comment]
У меня проявляется баг, на маленьком разрешении (на ноуте):
![image](https://cloud.githubusercontent.com/assets/1277422/11768125/a35e9ace-a1d4-11e5-9f5b-c1de78d526ad.png)

**Comment by yellow-sky** [comment]
Проверил
