### ISSUE TITLE
Использовать более презентабельные цвета

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#251]
![image](https://cloud.githubusercontent.com/assets/1277422/11749668/33317d24-a040-11e5-80d3-0399e74bde3d.png)

**Comment by karavanjo** [comment]
Цветовая гамма изменена на ту, которая была указана в примере:
![image](https://cloud.githubusercontent.com/assets/669999/11767821/a5b2cbaa-a1cb-11e5-8c64-660c15d0bc40.png)

**Comment by yellow-sky** [comment]
Проверил
