### ISSUE TITLE
Необходимо добавить подписи к осям

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#252]
![image](https://cloud.githubusercontent.com/assets/1277422/11749725/6da096ca-a040-11e5-99e5-0ade8ff2eaa9.png)

**Comment by karavanjo** [comment]
Добавлены подписи к вертикальной оси:
![image](https://cloud.githubusercontent.com/assets/669999/11766793/7645f3de-a1a7-11e5-8934-d7bbe9cc7bba.png)

**Comment by yellow-sky** [comment]
Проверил
