### ISSUE TITLE
При малом разрешении легенда отрисовывается поверх графиков

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#253]
![image](https://cloud.githubusercontent.com/assets/669999/11768510/7bb0cc84-a1e0-11e5-97c5-9f5ccf2420c6.png)

Связано с реализацией https://github.com/nextgis/nextgisweb_compulink/issues/250

**Comment by karavanjo** [comment]
Исправлено путем перерисовки диаграмм при изменении размеров окна. На совсем малых разрешениях возникнут ожидаемые артефакты в виде "обрезанных" надписей и появления полос прокрутки. Скриншот на разрешении 962 x 664 px показывает, что на этом разрешении артефактов нет, все отрисовано корректно:
![image](https://cloud.githubusercontent.com/assets/669999/11769457/92121ee8-a1f8-11e5-8803-5cfe46ab5cd4.png)

**Comment by yellow-sky** [comment]
Проверил
