### ISSUE TITLE
Подписи для подразделений на графике

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#254]
Сейчас подписи отображаются не все (скорее всего из-за своего размера).
Может можно поворачивать (на 60-90 градусов) подписи, чтобы они точно слезали?

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/11774333/1ade4fca-a245-11e5-8957-541be315fe50.png)

**Comment by yellow-sky** [comment]
Проверил
