### ISSUE TITLE
Проблема с отрисовкой границ контрола выбора подразделений в FF

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#260]
Связана с реализацией https://github.com/nextgis/nextgisweb_compulink/issues/257
![image](https://cloud.githubusercontent.com/assets/669999/11778359/ec7e3dbe-a264-11e5-99b0-3f1439b8a83f.png)

**Comment by karavanjo** [comment]
Исправлено:

FF:
![image](https://cloud.githubusercontent.com/assets/669999/11779113/33516b1c-a26a-11e5-998d-66c97419f590.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/669999/11779130/48eae156-a26a-11e5-9ed0-9ec21281b67e.png)

**Comment by yellow-sky** [comment]
Проверил
