### ISSUE TITLE
Надпись наезжает в контроле выбора подразделения

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#261]
![image](https://cloud.githubusercontent.com/assets/1277422/11779118/3759b2be-a26a-11e5-9458-32c62ab12bc2.png)

**Comment by karavanjo** [comment]
Исправлено в https://github.com/nextgis/nextgisweb_compulink/commit/8502ad3233d1be38b6e9c51b698237c5f5707eff при исправлении https://github.com/nextgis/nextgisweb_compulink/issues/260

**Comment by yellow-sky** [comment]
Проверил
