### ISSUE TITLE
Проблема при малом разрешении 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#262]
![image](https://cloud.githubusercontent.com/assets/1277422/11779351/799aa1aa-a26b-11e5-9220-31d600a249b0.png)

Не срочно!

**Comment by karavanjo** [comment]
Вариант с ограничением количества отрисовываемых символов:
![image](https://cloud.githubusercontent.com/assets/669999/11891632/72043ef2-a571-11e5-939d-bf5bdb768bb1.png)

**Comment by karavanjo** [comment]
Согласно https://github.com/nextgis/nextgisweb_compulink/issues/259 необходимо установить ограничение отрисовки подписей в 30 симоволов и использовать значение из `short_name`.
