### ISSUE TITLE
Добавить tooltips к диаграммам

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#263]

**Comment by karavanjo** [comment]
Добавлено.
К линейным графикам через добавление маркеров, т.к. на простых линиях tooltips не строятся:
![image](https://cloud.githubusercontent.com/assets/669999/11787862/01f7b9e2-a29f-11e5-8f02-2c38c7b8e4ab.png)
К столбчатым диаграммам:
![image](https://cloud.githubusercontent.com/assets/669999/11787878/1e427da8-a29f-11e5-866d-c24a1c68df82.png)

**Comment by yellow-sky** [comment]
Проверил
