### ISSUE TITLE
Оформление полей для ввода параметров в «Отчете о реализации проекта УЦН» 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#266]
Необходимо сделать оформление полей для ввода параметров в «Отчете о реализации проекта УЦН» таким же как в «Отчете о ходе строительства».
 
![image](https://cloud.githubusercontent.com/assets/1277422/11819244/dc417ef0-a36f-11e5-84ec-4a341368d9fe.png)

![image](https://cloud.githubusercontent.com/assets/1277422/11819247/e1608c64-a36f-11e5-9cae-9df50bef59f0.png)

**Comment by karavanjo** [comment]
Стилизация из страницы `"Отчет о ходе строительства"` применена к отчетам УЦН:
![image](https://cloud.githubusercontent.com/assets/669999/11835837/6fe4cc26-a3e7-11e5-9914-c50afce8cd5e.png)

**Comment by karavanjo** [comment]
Применена сетка в один столбец:
![image](https://cloud.githubusercontent.com/assets/669999/11836817/20af499a-a3ee-11e5-939f-49ec577e7204.png)

**Comment by karavanjo** [comment]
Claro стиль применен, окончательная версия:
![image](https://cloud.githubusercontent.com/assets/669999/11842677/31465f00-a416-11e5-9654-48079eb718aa.png)
