### ISSUE TITLE
Сделать точки на графике динамики меньшего размера

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#267]
Предлагается на линейном графике сделать точки размером в 1-3 пикселя, чтобы они были не заметны, но при наведении на 'линию' появлялся бы тултип.

**Comment by karavanjo** [comment]
Установлено значение в 1 px:
![image](https://cloud.githubusercontent.com/assets/669999/11840307/d7d29124-a405-11e5-8439-a91c061d3447.png)
