### ISSUE TITLE
Добавить контрол выбора проекта

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#269]
В «Отчет о ходе строительства» добавить параметр Проект. Без этого параметра нет возможности вывести в отчет данные по конкретному проекту тем более, если в этом проекте у объектов строительства не заполнены поля Субъект РФ и Муниципальный район. Поле для задания значения данного параметра должно отображаться над всеми остальными параметрами и представлять собой выпадающий список, в котором должна отображаться иерархия проектов, к которым имеет доступ пользователь. При этом если выбрана групповой ресурс, а не конкретный проект, то в отчете должны выводиться все проекты, которые находятся в данной группе.

**Comment by yellow-sky** [comment]
Связанный тикет: #268

**Comment by karavanjo** [comment]
Уточнение - должны быть доступны 2 варианта выбора?
1. По проекту - доступен элемент управления `Проект`, элементы управления `Субъект РФ` и `Район` недоступны.
2. По району - доступны `Субъект РФ` и `Район`, недоступен - `Проект`.
Верные сценарии?

**Comment by yellow-sky** [comment]
Да, все верно
20.12.2015 19:46 пользователь "Ivan Kavaliou" <notifications@github.com>
написал:

**Comment by karavanjo** [comment]
Реализована с использованием табов, подключена библиотека [tabtab.js](https://github.com/gijsroge/tabtab.js).

1. **Внешний вид для выбора по району**:
![image](https://cloud.githubusercontent.com/assets/669999/11977031/b1fb7774-a98f-11e5-8475-a3cd7361a72c.png)


2. **По объекту строительства**:
![image](https://cloud.githubusercontent.com/assets/669999/11977038/cc2568a8-a98f-11e5-8e0d-d4a151e575c7.png)


3. **С раскрытым деревом объектов**:
![image](https://cloud.githubusercontent.com/assets/669999/11977045/e235fa04-a98f-11e5-8fdb-b5a82524014b.png)

**Comment by karavanjo** [comment]
Необходимо реализовать отображение элементов управления выбора без использования табов. Все элементов управления должны быть видны и участвовать в конфигурировании отчета. Значения всех элементов управления должны уходить на серверную сторону.

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/11993097/79487544-aa3e-11e5-9d23-fc1412f559b6.png)

**Comment by karavanjo** [comment]
еобходимо разместить элемент управления "Проект" выше элементов управления "Субъект РФ" и "Район".

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/11993566/81af0b76-aa43-11e5-926c-c50f8f7ae81e.png)
