### ISSUE TITLE
Изменить поля в редакторе объекта строительства

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#296]
1)      Данные в полях содержащих даты отображать в формате дд.мм.гггг
2)      Изменить надпись «Название» на «Наименование»
3)      Изменить надпись «Разварка муфт План (шт)» на «Количество муфт (шт)»
4)      Изменить надпись «Строительства ГНБ переходов План (шт)» на «Количество спецпереходов (шт)»
5)      Изменить надпись «Монтаж точек доступа План (шт)» на «Количество точек доступа (шт)»
6)      Удалить поле «Разварка муфт Факт (шт)»
7)      Добавить поле «Количество кроссов (шт)»
8)      Изменить надпись «Проект строительства» на «Проект»
9)      Поле «Субподрядчик» разместить после поля «Проект»
10)   Удалить поле «Ссылка на ресурс»

**Comment by karavanjo** [comment]
`6) Удалить поле «Разварка муфт Факт (шт)»`
о каком поле идет речь? В редакторе есть поле `Разварка муфт План (шт)`, которое соответствует полю `fosc_plan`.

`7) Добавить поле «Количество кроссов (шт)»`
это поле соответствует атрибуту `cross_plan` класса `ConstructObject`? Сейчас оно называется `Разварка кроссов, План (шт)` в редакторе.

![image](https://cloud.githubusercontent.com/assets/669999/12412117/5bc72e64-be95-11e5-9b8c-8030ad7c7591.png)

**Comment by yellow-sky** [comment]
о каком поле идет речь? В редакторе есть поле Разварка муфт План (шт), которое соответствует полю fosc_plan.
Тут речь о том, что было два поля в первой версии (зак видел первую версию). Поэтому нужно было её поменять на второе поле, которое описывалось ниже.

это поле соответствует атрибуту cross_plan класса ConstructObject? Сейчас оно называется Разварка кроссов, План (шт) в редакторе.

Да, это именно это поле. Первоначальное название из кода просто было неверное.

**Comment by karavanjo** [comment]
Финальный вариант
![image](https://cloud.githubusercontent.com/assets/669999/12452481/a6a7dda6-bf9f-11e5-8563-5e7958c9c693.png)

**Comment by karavanjo** [comment]
Итоговая версия:
![image](https://cloud.githubusercontent.com/assets/669999/12454616/570d972c-bfa9-11e5-8622-66f729e105c4.png)

**Comment by karavanjo** [comment]
1. Изменить наименование пункта меню «Редактировать атрибуты» на «Открыть карточку»
2.  На карточке объекта сделать ширину поля «Проект» такой же как у остальных полей

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/12567662/817a8ff2-c3d1-11e5-916a-3f77752a0c40.png)
