### ISSUE TITLE
Связать комбо-бокс 'ВОЛС-СитПлан-ВОЛС+СитПлан' c деревом ресурсов и панелями типов слоев

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#3]
При выборе в верхнем выпадающем списке одного из значений, должна быть следующая реакция:
- Если выбрано ВОЛС, то в дереве должны отображаться только Групповые ресурсы (resource_group), Проекты строительства (FoclProject) и Структуры ВОЛС (FoclStruct) (!Возможно это лучше делать на сервере, если на клиенте будет сложно фильтровать элементы). 
При этом в правой панели должен остаться только один список - Слои ВОЛС.
- Если выбрано СитПлан, то в дереве должны отображаться только Групповые ресурсы (resource_group), Проекты строительства (FoclProject) и СитПланы(SituationPlan)
При этом в правой панели должен остаться только один список - Слои СитПлана.
- Если выбрано и то и другое - в дереве отображается все, в правой панели видны оба списка.

**Comment by karavanjo** [comment]
Логика DropDownButton довольно странная, был заменен в https://github.com/nextgis/nextgisweb_compulink/commit/59a25400b9787cd659304d93d159bd01c16b6ff4 на обычный dijit элемент управления Select.
