### ISSUE TITLE
Некорректная работа контрола по выбору проекта в отчете о ходе строительства 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#300]
![image](https://cloud.githubusercontent.com/assets/1277422/12545670/6b72c4e4-c355-11e5-8e9a-9183702d8501.png)

**Comment by karavanjo** [comment]
Исправлено в https://github.com/nextgis/nextgisweb_compulink/commit/ab90e06a9ff21ce227d8af05271ffa9fbede82dc
![image](https://cloud.githubusercontent.com/assets/669999/12552617/e69c77e0-c383-11e5-8c8b-e344510db5e7.png)
