### ISSUE TITLE
Выбор проекта в форме редактора Свойств объекта строительства

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#306]
Сейчас при загрузке окна редактора всегда выводится один и тот же проект (единственный). Хотя на самом деле проекта может и не быть.
Так же если проект установлен, то невозможно его обнулить.

**Comment by karavanjo** [comment]
Добавлено поле "Проект не выбран", которое в связанный атрибут на стороне сервера установит `None` значение.
![image](https://cloud.githubusercontent.com/assets/669999/12569408/acd6402a-c3df-11e5-8da7-711d32b54c6e.png)
