### ISSUE TITLE
Не открывается карточка объекта

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#308]
При попытке открыть карточку объекта строительства:
- Тестирование->Тестовый проект->Тестирование Реестра
- Тестирование->Тест ВОКЛ на уч....->Тест ВОКЛ на уч....
окно висит бесконечно. 
При этом все запросы отрабатывают.
При невозможности отобразить карточку объекта необходимо оповещать пользователя и закрывать это окно.

**Comment by karavanjo** [comment]
Происходит из-за https://github.com/nextgis/nextgisweb_compulink/issues/310

**Comment by karavanjo** [comment]
Исправлено в https://github.com/nextgis/nextgisweb_compulink/commit/e785fd82a3eea2bc40223bdbf5779a0bc8a25391
![image](https://cloud.githubusercontent.com/assets/669999/12567043/0a58f7e0-c3ce-11e5-9421-e3e78662969c.png)
