### ISSUE TITLE
  Некорректно работает выбор Региона/Района

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#312]
Некорректно работает выбор Региона/Района. Выбираю Чеченская республика, а в поле в результате подставляется Сергиево-Посадский район, Подольский район.

![image](https://cloud.githubusercontent.com/assets/1277422/12576463/e4ecf8d8-c424-11e5-8b3f-d5ba9627e84c.png)

**Comment by karavanjo** [comment]
Необходимо в дереве местоположений задавать идентификаторы `reg_` для регионов, `distr_` для районов. Сейчас используется единая схема и встречаются элементы с одинаковыми индентификаторами, что приводит к ошибка при выборе.
