### ISSUE TITLE
Не выводится ошибка, если сохранение в карточке объекта не произошло

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#315]
Если на сервере не сохраняется карточка объекта строительства, то пользователь об этом не узнает. Форма закрывается, но состояние объекта не меняется

**Comment by karavanjo** [comment]
Реализовано. В случае ошибки при сохранении на стороне сервера появится информационное окно:
![image](https://cloud.githubusercontent.com/assets/669999/12771582/5a222d28-ca3b-11e5-8493-0c44c84438db.png)
