### ISSUE TITLE
Помечать вертексы линий как крестики

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#332]
Можно ли помечать вертексы линий при выделении как перекрестие? Это очень похоже на десктоп и более понятно, что выбран не точечный объект.

Крайне желательно выделять выбранную линию другим цветом. Иначе не очень понятно, что она выбрана.

Может есть альтернативное оформление для селекта?

**Comment by karavanjo** [comment]
Выделение линий цветом и вертексами реализовано.
![select_lines](https://cloud.githubusercontent.com/assets/669999/13459458/d5664f3c-e084-11e5-9421-7a178ddf6ca4.gif)

**Comment by yellow-sky** [comment]
готово
