### ISSUE TITLE
Добавление новых линий

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#339]
Для возможности добавления новых линий на панели инструментов должны быть две кнопки - синяя и красная. Первая создает линии волс, вторая - спецпереходы.
После нажатия одной из кнопок должен ативироваться механизм добавления линий между точками. При клике пользователя по карте должно проверяться, есть ли точка под кликом ( с небольшим буфером) и если есть, считать что точка создана. После ввода первой точки от неё начинает тянуться резиновая линия, до того момента, пока пользователь не попадет по второй точке. 

Нужно что-то придумать с заполнением атрибутов новых объектов! возможно пересылать на сервер ид точечных.

**Comment by karavanjo** [comment]
Вариант иконок и подписей:
![create_vols_sp](https://cloud.githubusercontent.com/assets/669999/13173223/7e7bc074-d70d-11e5-8b15-c374dce07065.gif)

**Comment by yellow-sky** [comment]
Норм, поменять местами кнопки ВОЛС и спецпереход.

**Comment by karavanjo** [comment]
Сигнатура сервиса для создания новых линий:
тип - `PUT`
данные на вход:
```
line: {
    start: {
        ngwLayerId: \d+,
        ngwFeatureId: \d+
    },
    end: {
        ngwLayerId: \d+,
        ngwFeatureId: \d+
    },
    type: '[vols | stp]'
}```

**Comment by yellow-sky** [comment]
Вторая кнопка (спецпереходы) должна соединять только точки из слоя спецпереходов.

**Comment by karavanjo** [comment]
`Вторая кнопка (спецпереходы) должна соединять только точки из слоя спецпереходов`
Реализовано.

**Comment by yellow-sky** [comment]
Проверил
