### ISSUE TITLE
Выбор перекрывающихся объектов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#340]
При клике пользователя по перекрывающимся объектам (точкам или линиям) должно появляться контекстное меню с пунктами в которых указаны типы объектов, попавших в точку клика. При выборе пункта выделяется выбранный объект. Далее все так же как работает сейчас.

**Comment by karavanjo** [comment]
Контекстное меню для выбора добавлено:
![image](https://cloud.githubusercontent.com/assets/669999/13742057/c511b7ba-e9ea-11e5-8dc1-86150b9fbbaf.png)

Необходимо реализовать:
1. Скрывать меню по клику на пустом месте.
2. Не отображать меню, если выбирается один объект.

**Comment by yellow-sky** [comment]
Необходимо доделать\переделать:
1) Убрать круги
2) Уменьшить размер поиска объектов. Сейчас можно кликать в 100нях метрах от объекта и он будет находится. Лучше привязаться к пикселям и делать пересчет из размера пикселя. радиус поиска - 2-4 пикселя.

**Comment by karavanjo** [comment]
1. Индикатор оставил, т.к. к нему привязано контекстное меню - необходимо, чтобы у меню был HTML-элемент. Если это принципиально - индикатор можно убрать, заменив на прозрачный HTML элемент.
2. Добавил зависимый от разрешения карты размер охвата для поиска объекто. Сейчас он примерно совпадает с размером индикатора идентификации:

![loading](https://cloud.githubusercontent.com/assets/669999/13768954/b78a76de-ea8c-11e5-94ca-75e30f4bb7cb.gif)

**Comment by karavanjo** [comment]
1. реализовано в https://github.com/nextgis/nextgisweb_compulink/commit/f018e78c5c7b11d49afb4bb17fd496eb42d33f3e
