### ISSUE TITLE
Переместить кнопки редактирования в конец панели

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#341]
Все что связанно с редактированием необходимо выводить в конце панели инструментов после |

**Comment by karavanjo** [comment]
Инструменты редактирования вынесены в отдельную панель, которая определена в виджете `nextgisweb_compulink/compulink_editor/amd/ngw-compulink-editor/editor/EditorToolbar`.
![image](https://cloud.githubusercontent.com/assets/669999/13202027/690b5576-d89b-11e5-9e32-69426bff54d4.png)
