### ISSUE TITLE
Вывести название объекта строительства над панелью редактора атрибутов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#342]
Над панелью необходимо сделать некий бокс, в который выводить название объекта строительства, редактирование которого происходит в данный момент.

**Comment by yellow-sky** [comment]
Могу присылать название в темплейт, если это поможет

**Comment by karavanjo** [comment]
Реализовано.
Надпись "Атрибуты объекта" заменена на название объекта строительства - предполагается, что название у объекта есть всегда.
Надпись удалена, т.к. тогда возникает неопределенность - атрибуты выбранного объекта или атрибуты всего объекта строительства. Считаю, что пояснительной надписи `Для просмотра свойств объекта выделите его, кликнув по нему мышкой` достаточно.
Примеры:
![image](https://cloud.githubusercontent.com/assets/669999/14021044/d6f88226-f1ea-11e5-8df0-3f8e9307ca03.png)

![image](https://cloud.githubusercontent.com/assets/669999/14021051/e192284a-f1ea-11e5-9328-e7b6b4b1a125.png)

**Comment by yellow-sky** [comment]
Проверил
