### ISSUE TITLE
Откат одной точки

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#344]
Для отката одной точки необходимо добавить контекстное меню (дополнительно можно добавить кнопку на панель) для всех точечных объектов. 
При нажатии на км, должен уходить запрос на сервер с ид слоя и ид фичи. Возвращаются старые координаты или сообщение что их нет. При получении координат точка должна переехать в новое положение, а линии связанные с ней перестроиться, как если бы это было изменение положения вручную. После этого изменения сохраняются на сервере.

**Comment by yellow-sky** [comment]
Метод бекенда могу сделать. нужна сигнатура

**Comment by karavanjo** [comment]
Сигнатура:
Тип `POST`
URL `/compulink/editor/reset_point`

Parameters:
    `ngwLayerId: \d+,` 
    `ngwFeatureId: \d+`
