### ISSUE TITLE
Откат всего объекта сторительства

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#345]
В данный момент видится следующий вариант.
На панели инструментов должна быть кнопка, которая доступна только админам.
При нажатии по ней во всех актуальных слоях с линиями должны удаляться все объекты.
Все точечные слои должны быть очищены и заполнены из исходных.

**Comment by yellow-sky** [comment]
После этой операции необходимо перезагружать вектор на клиенте.

**Comment by karavanjo** [comment]
Добавлены иконки:
![undo](https://cloud.githubusercontent.com/assets/669999/13202147/740e65da-d8a0-11e5-9755-1e43bc31db5e.gif)

**Comment by yellow-sky** [comment]
При откате изменений объектов добавленные вручную фотографии и файлы не должны удаляться. Т.е. откат должен затрагивать только те фотографии, которые пришли с мобильного приложения. Если же фотографии или файлы были добавлены через веб интерфейс системы, то откат изменений их затрагивать не должен.
