### ISSUE TITLE
Построение линии на сервере

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#346]
В данный момент видится следующий вариант.
На панели есть отдельная кнопка, доступная только для админов.
При нажатии на неё уходит запрос на сервер о построении линии на сервере. После ответа клиент должен перезагрузить вектор.

**Comment by karavanjo** [comment]
адрес сервера для перестроения линии - `/compulink/editor/construct_line/{id:\d+}`

**Comment by karavanjo** [comment]
Функционал по обновлению векторного слоя добавлен.
Иконка для вызова перестроения линий:
![updates_lines](https://cloud.githubusercontent.com/assets/669999/13203621/27d7efc4-d8cd-11e5-885b-fbd86bdca120.gif)

**Comment by yellow-sky** [comment]
Не хватает проверки на админские права

**Comment by yellow-sky** [comment]
Готово
