### ISSUE TITLE
Если не выделен ни один объект, то «Атрибуты объекта» должны быть пустыми

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#353]
Сейчас есть приглашение/пояснение:
![image](https://cloud.githubusercontent.com/assets/669999/13173138/fa539628-d70c-11e5-8b73-e6a117cf5d28.png)
оно остается или сделать вообще пустым?

**Comment by yellow-sky** [comment]
Оставить подпись как на скриншоте
