### ISSUE TITLE
После удаления хотя бы одной фичи, кнопка пытается удалить не существующий объект

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#356]
Вместо предупреждения - не выбран объект, он спрашивает удалить, или нет.

**Comment by karavanjo** [comment]
Не воспроизводится:
![remove](https://cloud.githubusercontent.com/assets/669999/13762035/4a42a784-ea4d-11e5-9a2c-50897653ce5f.gif)

**Comment by yellow-sky** [comment]
Похоже, что исправлено предыдущими комитами
