### ISSUE TITLE
Неверно отрабатывает механизм выделения линий

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#371]
1. Входим в редактор
2. Выделяем линию
3. Без дополнительных кликов по карте выделяем другой линейный участок
Результат -> Выделяются вертексы нового участка, а цветом попрежнему выделен старый участок:
![image](https://cloud.githubusercontent.com/assets/1277422/13489857/61dd721e-e13a-11e5-8dba-e19dbb4216d1.png)

**Comment by karavanjo** [comment]
Подтверждаю. Аналогичное поведение у точек. Разбираюсь.
