### ISSUE TITLE
Расположить кнопки в следующем порядке

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#377]
![image](https://cloud.githubusercontent.com/assets/1277422/13741454/71456d3c-e9e7-11e5-8e2c-8f06729562e8.png)

**Comment by karavanjo** [comment]
Изменено на требуемый порядок.
![editor_panel](https://cloud.githubusercontent.com/assets/669999/13741707/bb444074-e9e8-11e5-9f69-6a07d2d87dac.gif)
