### ISSUE TITLE
Перестало работать снятие выделения по клику на пустом месте карты

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#381]

**Comment by karavanjo** [comment]
В дополнение - после активации меню либо сохранения изменений - перестает работать снятие выделения по клику на пустом месте карты и не активируется инструмент модификации.

**Comment by yellow-sky** [comment]
Иногда проявляется еще такое поведение - после нескольких кликов по объектам, при выборе точки и попутке перетянуть её в новое положение, тянется карта а не точка.
