### ISSUE TITLE
Кнопка добавления файлов в окне информации

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#384]
В окне информации об объекте (инфотул), на основной карте и в редакторе, 
на вкладках Фото и Документы добавить кнопку: Добавить (в виде +).
При нажатии этой  кнопки появляется окно выбора файлов. При выборе соответствующего файла должна происходить его загрузка и прикреплению к соответствующему объекту.
При этом Description должно формироваться в соответствии со следующем правилом:

[веб] Имя пользователя, время добавления 

После завершении операции содержание окна должно обновится.

**Comment by karavanjo** [comment]
Удаление/добавление реализовано для фото:
![animation](https://cloud.githubusercontent.com/assets/669999/14784420/4dc3d8d4-0afe-11e6-8d39-12f5adce45a3.gif)

**Comment by BishopGIS** [comment]
Крестик [x] как-то логичнее, а то минус - непривычно.

**Comment by simgislab** [comment]
ого, нам всё это нужно в ядре

**Comment by karavanjo** [comment]
Добавить фильтрацию значений по расширению файлов.
для фото - `.png`, `.jpg`, `.jpeg`, `.gif`
для файлов - `.docx`, `.doc`, `.xls`, `.xlsx`, `.zip`, `.rar`

**Comment by karavanjo** [comment]
Фильтры добавлены, функционал применен к вкладке файлов:
![doc_photo](https://cloud.githubusercontent.com/assets/669999/14952132/77de5532-1066-11e6-9910-5bb4908ed078.gif)

**Comment by yellow-sky** [comment]
Работает
