### ISSUE TITLE
Рамка для Фото и Файлов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#386]
В окне информации об объекте (инфотул), на основной карте и в редакторе, 
на вкладках Фото и Документы 
выводить зеленую рамку для всех фото и файлов, у которых в Description !НЕТ! текста [веб].
Остальные должны выводится так же как и сейчас.

**Comment by karavanjo** [comment]
Реализовано:
1. Добавлена метка `[WEB]` для описания файлов и фото, загружаемых через веб-интерфейс.
2. Файлы, загруженные через веб имеют зеленую рамку и пиктограмму удаления. Файлы, загруженные через мобильное приложение - удалить через интерфейс просмотра нельзя.
![web_mark](https://cloud.githubusercontent.com/assets/669999/15024400/6b4ae1d6-123d-11e6-9c4f-52c1583d9d6e.gif)

**Comment by karavanjo** [comment]
Замечания после показа:
зеленую рамку применить к фотографиям из мобильного приложения, серую - к загруженным через WEB.

**Comment by yellow-sky** [comment]
Работает
