### ISSUE TITLE
Общее по Печать текущей карты из веб-браузера

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#387]
В веб-приложении должна быть обеспечена возможность печати текущей карты из веб-браузера с возможностью указания элементов карты, выводимых на печать (стрелка на север, масштабная линейка и т.п.).

**Comment by karavanjo** [comment]
Реализован компонент для печати карты.
Логика работы:
1. При нажатии на кнопку печати появляется модальное окно, перекрывающее окно карты "Печать карты" с элементами управления, позволяющими выбрать формат:
![image](https://cloud.githubusercontent.com/assets/669999/14670425/cb293a24-06f5-11e6-8f88-8585df7fceb2.png)
2. В нижней части окна находится элемент, отображающий карту в зависимости от реальных размеров выбранного формата:
![image](https://cloud.githubusercontent.com/assets/669999/14670516/1e0624c8-06f6-11e6-9964-84d62aa9b2dc.png)
3. При нажатии на кнопку "Печать" вызывается окно предпросмотра с установленным форматом для печати.

Примечание:
1. В FF средствами JS вызвать окно предпросмотра нельзя, только системный диалог.
2. В FF сейчас в системного диалоге предпросмотра не устанавливается формат листа, выбранный в диалоге печати - еще в работе.
