### ISSUE TITLE
Наименования объектов в контекстном меню

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#389]
Непонятные наименования объектов во всплывающем контекстном меню. Наименования объектов в интерфейсе редактирования должны быть такими же как и в интерфейсе просмотра.
![image](https://cloud.githubusercontent.com/assets/1277422/14044002/1c29fd8c-f29c-11e5-929b-d0023e0d2a4a.png)

**Comment by karavanjo** [comment]
Если делать по аналогии с идентификационным меню, то:
1. Применить шаблон `[Тип объекта]: #[Номер объекта] ([Название объекта строительства])`
2. Объект строительства везде будет одинаков, т.к. редактируется всегд один объект строительства.

Итого:
Вариант 1.
Без `text-overflow:ellipsis`:
![image](https://cloud.githubusercontent.com/assets/669999/14233128/1548bfde-f9c8-11e5-95a0-d336069da029.png)

Вариант 2. 
С `text-overflow:ellipsis`, максимальная ширина 250px:
![image](https://cloud.githubusercontent.com/assets/669999/14233115/d8e57b2c-f9c7-11e5-9ec3-5d02520c46a0.png)

**Comment by karavanjo** [comment]
По результатам обсуждения:
1. Применить шаблон `[Тип объекта]: #[Номер объекта]`
2. Поле `[Тип объекта]` должно соответствовать значениям `identify_name` в файлах описания слоев, расположенных в директории [actual_real_layers_templates](https://github.com/nextgis/nextgisweb_compulink/tree/bc58ac6f69e8d371a10d18c549ebb5e92336cb91/nextgisweb_compulink/compulink_admin/actual_real_layers_templates)

Итого:
![image](https://cloud.githubusercontent.com/assets/669999/14233196/73f41d06-f9ca-11e5-8eb2-ff32c116f29d.png)
