### ISSUE TITLE
Система справочников

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#39]
Справочник - ресурс, типа таблица, содержащая поля ключ - значение. Справочник должен иметь  собственное уникальное название - keyname (на англ, пример building_type) и display_name (на русском, Тип здания).

Необходимый функционал:
1) Возможность редактировать (добавлять, удалять, редактировать записи)
2) Получать доступ к справочникам программно из NGW
3) Получать доступ к справочникам через rest api (только чтение)
4) Необходимые запросы:
 * получить справочник в виде списка - все пары ключ-значения (на программном уровне, через rest)
 * получать значение справочника по ключу (на программном уровне) 

5) При удалении ресурса, сама таблица удаляться не должна, как и остальные ресурсы сейчас, в целях сохранения целостности. 
6) Желательно иметь возможность задать тип данных для ключа - string, int, float (как у метаданных). Если данный функционал занимает много времени - сделать что и ключ и значение типа string.

Необходима реализация в виде подмодуля Compulink экстеншена  (желательно в отдельной подпапке).

**Comment by karavanjo** [comment]
Хорошая тема. Когда ожидают от нас реализацию?

**Comment by drnextgis** [comment]
Модуль [nextgisweb_lookuptable](https://github.com/nextgis/nextgisweb_lookuptable).
