### ISSUE TITLE
Добавить интерфейс просмотре таблицы отклонений

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#413]
В пункт меню отчеты добавить пункт - Отклонения от проекта.
При клике по нему необходимо открывать новую страничку с выбором дерева доступных объектов строительства и переключателем - (выводить утвержденные).
При запросе необходимо выводить все отклонения для выбранных объектов строительства из таблицы отклонений. 
При клике по строчке необходимо выводить карту с включенным объектом строительства.

**Comment by yellow-sky** [comment]
Поля таблицы:
1. Наименование ВОЛС
2. Тип объекта
3. Номер объекта
4. Отклонение в метрах

При включении галки Выводить утвержденные, добавлять следующие поля:
5. Отклонение утверждено
6. Автор утверждения
7. Дата\Время утверждения
8. Комментарий к отклонению

**Comment by yellow-sky** [comment]
Доделать 
При клике по строчке необходимо выводить карту с включенным объектом строительства.

**Comment by karavanjo** [comment]
`При клике по строчке необходимо выводить карту с включенным объектом строительства.`
Реализовано.

![413](https://cloud.githubusercontent.com/assets/669999/16192490/530ec234-36f2-11e6-921e-f4decacafb84.gif)

**Comment by yellow-sky** [comment]
Работает
