### ISSUE TITLE
Интерфейс утверждения отклонений

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#415]
В пользовательском интерфейсе monitoring map, в инфотуле необходимо показывать кнопку - утвердить отклонение. Она должна быть активна, только если есть соответствующее право.
При нажатии должен вызываться метод сервиса, для утверждения. После этого должна перерисовываться карта.

**Comment by yellow-sky** [comment]
Уточнения:
Cделать утверждение через контекстное меню, которое должно открываться при щелчке правой кнопкой мыши по объекту на главной кнопке. Выбор объектов, оказавшихся в зоне клика, нужно сделать по аналогии с интерфейсом редактирования. После выбора объекта в контекстном меню необходимо открывать контекстное окно (JS) с вводом комментария и кнопкой - Утвердить.

**Comment by karavanjo** [comment]
Реализовано:
![415](https://cloud.githubusercontent.com/assets/669999/16431712/8457d04e-3d8a-11e6-93a4-2dd336542bb5.gif)

**Comment by karavanjo** [comment]
1. Добавить поле "Комментарий" к окну утверждения отклонения.
2. Переименовать "Да" в "Утвердить".

**Comment by karavanjo** [comment]
Реализовано.
В `XHR` уходит поле `comment`.
![415](https://cloud.githubusercontent.com/assets/669999/16447397/154d6144-3df5-11e6-987e-5049d8c9adf0.gif)

**Comment by karavanjo** [comment]
Сделать поле "Комментарий" элементом `<area>`

**Comment by karavanjo** [comment]
Поле ввода заменено на `textarea`.
Высота - 4 линии текста.
![415](https://cloud.githubusercontent.com/assets/669999/16450939/9f2b3ff4-3e08-11e6-863d-d6db5671a9a9.gif)

**Comment by yellow-sky** [comment]
Готово
