### ISSUE TITLE
Серверный метод для утверждения отклонения

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#416]
1. При вызове должны проверяться права на возможность утверждения.
2. При вызове в него передаются ОС, тип объекта, ид объекта.
3. При вызове записывается информация кто и когда утвердил, меняется флаг
4. Так же записывается изменения в таблице отклонений (флаг).

**Comment by karavanjo** [comment]
Требование 1. должно учитываться в сервисе https://github.com/nextgis/nextgisweb_compulink/issues/447 с маршрутом `compulink.deviation.identify` по URL `/compulink/deviation/identify` при выдаче объектов для контекстного меню.

**Comment by karavanjo** [comment]
URL: `/compulink/deviation/apply`
Параметры:
`layerType` - тип слоя,
`layerId` - id слоя,
`featureId` - id объекта.

**Comment by yellow-sky** [comment]
Работает
