### ISSUE TITLE
Общее по проигрывателю строительства

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#417]
При клике по ОС в таблице под картой пункт меню Проиграть - открывается новой окно с картой и выбранным ОС.
Отображаются только панель сверху + 2 панель с элементами упр проигрывателя.
!Возможно будет отображаться панель с типами слоев и легендой.
На клиент загружается вектор.
При проигрывании отображаются только объекты с датой строительства <= текущей виртуальной даты.
Необходима регулировка скорости проигрывания.
Необходимо подумать, как можно показывать случайное фото с объекта.

**Comment by karavanjo** [comment]
Первая версия плеера:
1. Указаны количества построенных за день объектов.
2. Проигрывание со скоростью 1 день в секунду. Параметр настройки скорости реализован, но еще не связан с UI.
3.По клику линия времени перемещается в место клика и слой обновляется.
4. Останов по нажатию на иконку "Стоп".
![player_v 0 0 1](https://cloud.githubusercontent.com/assets/669999/15315149/90cfd2dc-1c1e-11e6-8164-a18d027e1b8a.gif)

**Comment by karavanjo** [comment]
Вторая версия, с учетом https://github.com/nextgis/nextgisweb_compulink/issues/420, https://github.com/nextgis/nextgisweb_compulink/issues/421, https://github.com/nextgis/nextgisweb_compulink/issues/422, https://github.com/nextgis/nextgisweb_compulink/issues/424, https://github.com/nextgis/nextgisweb_compulink/issues/425, https://github.com/nextgis/nextgisweb_compulink/issues/427, https://github.com/nextgis/nextgisweb_compulink/issues/428.

![player_v 0 2](https://cloud.githubusercontent.com/assets/669999/15998553/de1afa42-3147-11e6-844f-1a187496e1e3.gif)

**Comment by yellow-sky** [comment]
В общем большинстве выполнено. Отдельные недочеты - отдельными тикетами.
