### ISSUE TITLE
Добавить названия файлов к миниатюрам файлов

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#419]

**Comment by karavanjo** [comment]
Реализовано:
![419](https://cloud.githubusercontent.com/assets/669999/16075852/33468bc8-32f9-11e6-91eb-dad0384906ad.gif)

**Comment by karavanjo** [comment]
Есть ли замечания по реализации? Если нет - закрываем.

**Comment by yellow-sky** [comment]
Фидека нет. Пока закрываем.
