### ISSUE TITLE
Изменить размер окна до минимально возможного

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#422]

**Comment by karavanjo** [comment]
Ширина оставлена без изменений, высота установлена в 145px, добавлено изменение размеров окна:
![image](https://cloud.githubusercontent.com/assets/669999/15647740/278f40be-266e-11e6-822e-629c9ecd0e12.png)

**Comment by yellow-sky** [comment]
Можно зафиксировать высоту окна?

**Comment by yellow-sky** [comment]
работает
