### ISSUE TITLE
Разработать регулятор скорости проигрывания

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#427]

**Comment by karavanjo** [comment]
Регулятор скорости реализован. Доступные варианты на скриншотах:
![image](https://cloud.githubusercontent.com/assets/669999/15997731/10393050-3140-11e6-8c1d-f4becf7ae019.png)
![image](https://cloud.githubusercontent.com/assets/669999/15997732/131e477e-3140-11e6-9bc9-4370dae305c4.png)

**Comment by yellow-sky** [comment]
работает
