### ISSUE TITLE
Не отображаются объекты после даты их создания в начале ленты времени

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#429]
Вместе с тем, перед минимальной датой строится группа объектов.
![429](https://cloud.githubusercontent.com/assets/669999/16007853/6ad1fd48-317d-11e6-96cf-758a9f138d42.gif)

**Comment by karavanjo** [comment]
Исправлено:
![429](https://cloud.githubusercontent.com/assets/669999/16008469/c69649ce-3180-11e6-8492-d59807ca0514.gif)

**Comment by yellow-sky** [comment]
Работает
