### ISSUE TITLE
Открывать карту с экстентом выбранного объекта

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#438]
Передавать параметры
`object_type`
`object_num`
Серверный метод:
`/compulink/resources/object_extent?resource_id=2371&object_type=optical_cable&object_num=82`

**Comment by karavanjo** [comment]
Реализовано:
![438](https://cloud.githubusercontent.com/assets/669999/16195919/5945327a-3704-11e6-889c-aacec56a736f.gif)

**Comment by yellow-sky** [comment]
Работает
