### ISSUE TITLE
Масштабы отображений для векторных слоев

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#440]
На масштабе, при котором точки сливаются в одну сплошную черную линию, точки не отображать.

**Comment by karavanjo** [comment]
Функционал должен быть применен как для редактора, так и для проигрывателя строительства?

`Замечание`: если функционал будет применен для проигрывателя, то для большого по экстенту ресурса, точки отображаться не будут (ведь на маленьком зуме они будут сливаться в линию) - но как тогда увидеть прогресс по строительству объекта?

**Comment by yellow-sky** [comment]
Только для плеера.
Будут видны линии.
09.07.2016 22:17 пользователь "Ivan Kavaliou" <notifications@github.com>
написал:

**Comment by karavanjo** [comment]
Реализовано. Масштаб, начиная с которого точки должны быть скрыты, задается [здесь](https://github.com/nextgis/nextgisweb_compulink/blob/f0b168e06b1541599bc8bba417401aa52e903385/nextgisweb_compulink/compulink_editor/amd/ngw-compulink-editor/player/Display.js#L352). Сейчас установлен в 10.

**Comment by karavanjo** [comment]
Должны скрываться точки с типом слоя `Отметки трассы ВОЛС` и `Отметки спецпереходов`.

**Comment by karavanjo** [comment]
Реализовано. Необходимо ли изменить текущее значение [зума 10](https://github.com/nextgis/nextgisweb_compulink/blob/f0b168e06b1541599bc8bba417401aa52e903385/nextgisweb_compulink/compulink_editor/amd/ngw-compulink-editor/player/Display.js#L352)?

**Comment by yellow-sky** [comment]
Работает
