### ISSUE TITLE
Fade In эффект для векторного слоя.

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#441]
Построенные участки выводить не сразу целиком, а отрисовывать постепенно. На сам эффект - 0.9 с.

**Comment by karavanjo** [comment]
Применен механизм построения, разбивающий группу объектов на 5 частей в секундном промежутке и отрисовывающий через 0, 0.2, 0.4, 0.6, 0.8 секунд.
Сейчас этот же механизм используется при клике в любом месте графика, т.е. без проигрывания - так как клики строят объекты от начала до места клика - видна анимация.

![441](https://cloud.githubusercontent.com/assets/669999/16687537/e65d39ac-4521-11e6-869a-a22a8c113e4d.gif)

**Comment by yellow-sky** [comment]
Работает. Пока закрываем.
