### ISSUE TITLE
Включить отображение слоев с проектными данными

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#442]
На карте, которая открывается при клике по строке с отклонениями в таблице отклонений, необходимо включать отображение слоев с проектными данными, чтобы сразу были видно отклонение от проекта.

**Comment by karavanjo** [comment]
Необходимо, чтобы:
1. Были включены только `Проектные данные`
2. Были включены и `Проектные данные` и `Фактические данные`

**Comment by yellow-sky** [comment]
2. Были включены и Проектные данные и Фактические данные

**Comment by karavanjo** [comment]
Реализовано.
![442](https://cloud.githubusercontent.com/assets/669999/16265570/ba591100-3888-11e6-9f5a-4e679015112e.gif)

**Comment by yellow-sky** [comment]
Работает
