### ISSUE TITLE
Механизм массового утверждения отклонений от проекта

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#449]
Если объектов много, то утверждение отклонений по одному объекту может превратиться в очень трудоемкую задачу. В отчете об отклонениях сделать столбец с чекбоксами и копку «Утвердить отклонения». В этом случае пользователь сможет поставить чекбоксы в нужных строках и нажать кнопку «Утвердить отклонения». Ему откроется окно для ввода комментариев к утверждению. После этого все выделенные объекты получат статус утвержденных.

**Comment by karavanjo** [comment]
Для реализации необходим сервис https://github.com/nextgis/nextgisweb_compulink/issues/453

**Comment by yellow-sky** [comment]
Работает
