### ISSUE TITLE
Не выводятся поля Дата и время утверждения и Комментарий в таблице с утверждениями

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#452]

**Comment by karavanjo** [comment]
Обнаружена ошибка при выводе даты, исправлено в https://github.com/nextgis/nextgisweb_compulink/commit/26ddcd24e4176303ab64d877092695d95eba5c38.

По остальным значениям проблем не обнаружено:
![image](https://cloud.githubusercontent.com/assets/669999/16583445/3a759068-42be-11e6-8ffe-1563904b7658.png)

**Comment by yellow-sky** [comment]
Работает
