### ISSUE TITLE
Некорректное построение окна утверждения отклонений

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#457]
После обновления версии Dojo в https://github.com/nextgis/nextgisweb/commit/1df803a371267abd5c5ddd3aec005f2a61d80c9d

![image](https://cloud.githubusercontent.com/assets/669999/16619330/57695fa0-4396-11e6-9f66-4799431daea2.png)

**Comment by karavanjo** [comment]
Исправлено:
![image](https://cloud.githubusercontent.com/assets/669999/16619409/99c79d76-4396-11e6-89f2-eb808dbfbb98.png)

**Comment by yellow-sky** [comment]
Работает
