### ISSUE TITLE
Не открывается окно инфотула

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#458]
Если вывести окно идентификации объекта, затем отключить инфотул (не закрывая окно идентификации!!!), то после включения инфотула окно идентификации объекта не открывается.

**Comment by karavanjo** [comment]
Связано с https://github.com/nextgis/nextgisweb_compulink/issues/459, пофикшено в https://github.com/nextgis/nextgisweb_compulink/commit/97b3a42f2d282d26737b286789a3cd30f22a4cf7

**Comment by yellow-sky** [comment]
Работает
