### ISSUE TITLE
Переделать правый клик на линк внутри таблицы инфотула

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#465]
Делать кастомную проверку атрибутов, и если есть поле:

```Есть отклонение от проекта```
которое == ```Да```
то выводить его толстым красным
 и выводить сслыку  ```Утвердить```.

При нажатии ???делаем проверку??? и выводим окно.

**Comment by karavanjo** [comment]
Реализовано.
![465](https://cloud.githubusercontent.com/assets/669999/16902506/487ab2ce-4c69-11e6-962c-a7aa6d5643f4.gif)

**Comment by yellow-sky** [comment]
Работает
