### ISSUE TITLE
Порядок отрисовки слоев

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#466]
Сейчас появляются ошибки при включении выключении слоев в панели типов слоев.
Если включать\выключать, то порядок отрисовки (снизу-вверх) сбивается, и некоторые слои (обычно те, которые вкл\выкл), начинают рисоваться поверх всего.
То же самое проявляется при открытии карты из таблицы отклонений - каждый раз порядок отрисовки слоев разный.

**Comment by karavanjo** [comment]
Готово к тестированию.

**Comment by yellow-sky** [comment]
Все корректно вроде
