### ISSUE TITLE
При перетягивании точки должны перерисоваться линни, которые с ней связаны

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#470]

**Comment by karavanjo** [comment]
Реализовано:
![470](https://cloud.githubusercontent.com/assets/669999/17207552/cf2bc004-54bd-11e6-9d6f-1bf3dde511b4.gif)

**Comment by karavanjo** [comment]
merged with master by https://github.com/nextgis/nextgisweb_compulink/commit/b586763ec923bc30e06725bb43d2c1105b84965d

**Comment by yellow-sky** [comment]
Работает
