### ISSUE TITLE
Изменить инструмент по умолчанию для страницы редактирования

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#476]
Выделение и перетаскивание работает, но для этого необходимо активировать соответствующий инструмент на панели. Раньше он был активирован по-умолчанию, но теперь по умолчанию активируется инфоотул. Для этой страницы нужно активировать инструмент перетаскивания.

**Comment by karavanjo** [comment]
Реализовано.

**Comment by yellow-sky** [comment]
Работает
