### ISSUE TITLE
Добавить проверку прав

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#479]
При утверждении отклонений от проекта, если у пользователя нет прав, то система все равно дает нажать ссылку «Утвердить» и даже выводит окно для ввода комментариев. 
При этом никаких сообщений, что у пользователя нет доступа на утверждений отклонений не выводится. 
При щелчке по ссылке «Утвердить» выводить сообщение, что нет доступа.

**Comment by yellow-sky** [comment]
Напиши какой нужен метод на бэкенде, я сделаю быстро

**Comment by karavanjo** [comment]
Реализовано для попапа идентификации - если нет прав выводится только надпись "Да", ссылка "Утвердить" не выводится. Проверка осуществляется в момент рендеринга попапа асинхронно, на скорость рендеринга полей не влияет:
![image](https://cloud.githubusercontent.com/assets/669999/18247697/981943ce-737c-11e6-9deb-72baff8e5bcc.png)

**Comment by yellow-sky** [comment]
Работает
