### ISSUE TITLE
Изменить поведение таблицы под картой статистики

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#480]
На карте «Статистика» при двойном щелчке по объекту строительства в таблице под картой открывать карту с отображенным объектом строительства, которая сейчас открывается при выборе во всплывающем меню пункта «Показать объект на карте»

**Comment by karavanjo** [comment]
Реализовано. Требует тестирования на стенде с реальными данными.

**Comment by yellow-sky** [comment]
Работает
