### ISSUE TITLE
При многократном нажатии на кнопку воспроизведения построение объектов нарушается

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#490]
Исправление - блокировать кнопку воспроизведения при включении проигрывания объектов строительства

**Comment by yellow-sky** [comment]
Так же нужно блокировать, когда ползунок стоит в конце полосы проигрывания

**Comment by karavanjo** [comment]
Реализовано в https://github.com/nextgis/nextgisweb_compulink/commit/caa60d167fab28e46edb95cc4f45784d949e9e5c

`Так же нужно блокировать, когда ползунок стоит в конце полосы проигрывания`
вынесено в https://github.com/nextgis/nextgisweb_compulink/issues/491
