### ISSUE TITLE
Свернуть дерево слоев до 1 уровня

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#496]

**Comment by karavanjo** [comment]
В текущей реализации при проставлении галки на родительской ветке - родительская ветка разворачивается, поэтому инициализация дерева завершается следующим образом (все `неотмеченные` - свернуты, `отмеченная` - развернута):
![image](https://cloud.githubusercontent.com/assets/669999/21482911/3f62f5ba-cb8b-11e6-927f-43099ec505cb.png)

@yellow-sky, устроит ли такой вариант?

**Comment by yellow-sky** [comment]
НА старте нужно все сворачивать

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/21483047/5d27bde0-cb8d-11e6-89a9-5d491213edf5.png)
