### ISSUE TITLE
«Отображение нового фото должно производиться с использованием эффекта “проявления”»

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#514]
Увеличить время эффекта, чтобы он был заметен

**Comment by karavanjo** [comment]
Увеличено с 200ms до 1000ms:
![514](https://cloud.githubusercontent.com/assets/669999/21344502/2193f4f4-c6ad-11e6-87b9-80f6d0bcde63.gif)
