### ISSUE TITLE
Фотография не должна закрывать строящуюся трассу

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#516]

**Comment by karavanjo** [comment]
Обсудить вариант со статической картинкой

**Comment by karavanjo** [comment]
Принятое решение после обсуждения - фотография должна размещаться в левом нижнем углу страницы, ее местоположение на карте необходимо указывать линией-указателем от фотографии до целевой точки.

**Comment by karavanjo** [comment]
Реализовано.
Демонстрация доступна по [ссылке](https://youtu.be/uMhwMLr34jM).

![image](https://cloud.githubusercontent.com/assets/669999/22407396/b7aef9dc-e676-11e6-88dc-91afe1744228.png)

**Comment by yellow-sky** [comment]
Сдали на проверку
