### ISSUE TITLE
Выделение участка

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#517]
Нужно как-то более явно выделять принятый участок трассы. Для этого предлагаю отображать маркеры начала и окончания принятого участка по аналогии с отображением начальной и конечной точки маршрута в Яндекс.Картах. Мне кажется нужно изменить цвет выделения границ принятого участка, т.к. он сливается с оформлением способа прокладки в грунте. Как вариант предлагаю попробовать зеленую границу.

**Comment by karavanjo** [comment]
Установлены параметры `z-index` для отображения слоев принятых участков поверх `mapserver` слоев и изменена цветовая схема.

Предлагаемая цветовая схема:
![image](https://cloud.githubusercontent.com/assets/669999/21381845/b28f3d62-c76e-11e6-965c-71a07258d8b9.png)
где:

| Цвет        | Назначение           | Толщина линии |
| ------------- |:-------------|:------------|
| ![image](https://cloud.githubusercontent.com/assets/669999/21381911/026f683e-c76f-11e6-99ba-2ac2c8aad5ee.png)     | Принятый участок |  4px |
| ![image](https://cloud.githubusercontent.com/assets/669999/21381982/53b40182-c76f-11e6-9614-15ccf77f3df5.png) | Выделенный принятый участок | 8px |
| ![image](https://cloud.githubusercontent.com/assets/669999/21382002/6edfd832-c76f-11e6-932c-c08d63840db0.png) | ВОЛС     | 4px |

**Comment by karavanjo** [comment]
Изменена цветовая схема:
![image](https://cloud.githubusercontent.com/assets/669999/21565555/a19c3774-ceaa-11e6-9cde-ff08fc9d16e3.png)

где:

| Цвет        | Назначение           | Толщина линии |
| ------------- |:-------------|:------------|
| ![image](https://cloud.githubusercontent.com/assets/669999/21565623/6f428da4-ceab-11e6-921e-f3216f22c54e.png)  | Принятый участок |  4px |
| ![image](https://cloud.githubusercontent.com/assets/669999/21565612/5ea616aa-ceab-11e6-963d-de39cf37ecb4.png) | Выделенный принятый участок | 8px |
| ![image](https://cloud.githubusercontent.com/assets/669999/21565630/7edc2324-ceab-11e6-81f9-25d9fff15120.png) | ВОЛС     | 4px |

**Comment by yellow-sky** [comment]
Работает
