### ISSUE TITLE
Переименовать кнопку

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#521]
Кнопку «Закрыть» в окне задания свойств принятого участка нужно переименовать на «Отмена», т.к. в результате нажатия этой кнопки происходит отмена создания выделенного участка, а не просто закрывается окно.

**Comment by karavanjo** [comment]
Переименовано:
![image](https://cloud.githubusercontent.com/assets/669999/21382538/535fd1a4-c772-11e6-9575-2ce79140eea6.png)
