### ISSUE TITLE
Заполнение поля

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#522]
5)      В окне задания свойств отмеченного участка поле Принял должно быть недоступно для редактирования и автоматически заполняться ФИО текущего пользователя

**Comment by karavanjo** [comment]
Реализовано:
![522](https://cloud.githubusercontent.com/assets/669999/21426445/0275293a-c860-11e6-83a7-c43f2747af2a.gif)

**Comment by yellow-sky** [comment]
Вомзожно придется что-то сделать с заполнением, но пока закрываем
