### ISSUE TITLE
Избавиться от скрола

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#525]
![image](https://cloud.githubusercontent.com/assets/1277422/21483322/55a57144-cb91-11e6-89c2-e6e87c2a3aeb.png)

**Comment by karavanjo** [comment]
Высота контейнера таймлайна была увеличена с 175 до 180px для того, чтобы скролл не появлялся:
![image](https://cloud.githubusercontent.com/assets/669999/21508097/00fbb6c2-cc8f-11e6-87de-d42b25e539bc.png)

Однако нужны данные для тестирования.
В `Chromium 48.0.2564.82 Ubuntu 15.04 (64-bit)` скролла не наблюдалось изначально, возможно в конкретном сценарии тестирования он был.

**Comment by yellow-sky** [comment]
Воспроизводится

**Comment by karavanjo** [comment]
Firefox 44.0 Ubuntu 15.04 (64-bit)
![image](https://cloud.githubusercontent.com/assets/669999/23228038/286f90ae-f94c-11e6-9ea4-dceb55fcdf36.png)

Chromium 48.0.2564.82 Ubuntu 15.04 (64-bit)
![image](https://cloud.githubusercontent.com/assets/669999/23228045/31ef3850-f94c-11e6-9bf5-b1ee27f0850e.png)

**Comment by yellow-sky** [comment]
Работает
