### ISSUE TITLE
Реализовать виджет для управления записью видео

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#528]

**Comment by karavanjo** [comment]
Реализовано.

### Создание нового видео
1. Клик по кнопке "Записать"
2. Диалог подтверждения записи -> клик `OK`
3. Блокирование кнопки записи во время создания видео
4. Отправка POST запроса на `/compulink/player/video`
5. Обновление списка для отображения создаваемого видео (GET на `/compulink/player/video`) 
6. Обращение к GET `/compulink/player/video/status/{{videoId}}` раз в 5 сек, как только получен status == 'ready', обновление списка видео, разблокирование кнопки записи.

Демо:
![create](https://cloud.githubusercontent.com/assets/669999/22161844/1d01338e-df5d-11e6-9e4a-3c205292677b.gif)

### Удаление видео
1. Клик по кнопке "Удалить"
2. Диалог подтверждения удаления -> клик `Удалить`
3. Обращение к DELETE `/compulink/player/video`
4. Обновление списка видео.

Демо:
![remove](https://cloud.githubusercontent.com/assets/669999/22161963/9b5d5f32-df5d-11e6-9d0a-77912539bf23.gif)

**Comment by yellow-sky** [comment]
Готово
