### ISSUE TITLE
Разработать CRD сервисы для управления видео

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#532]
Описание структуры данных видеофайла:
```
// VideoInfoDetail
{
    id: [Number],
    name: [String],
    size: [String],
    url: [String],
    created_date_time: [Number], // ms since January 1, 1970, 00:00:00
    status: [String('creating', 'ready')]
}

// VideoInfo
{
    id: [Number],
    name: [String],
    status: [String('creating', 'ready')]
}
```

**Получение списка файлов**:

| Параметр| Спецификация|
| ------------- |-------------|
| Type      | GET |
| Parameters | - |
| Result| [VideoInfoDetail, ... , VideoInfoDetail]|

**Удаление видео**:

| Параметр| Спецификация|
| ------------- |-------------|
| Type      | DELETE |
| Parameters | id: [Number]|
| Result| 200 OK|

**Создание видео**:

| Параметр| Спецификация|
| ------------- |-------------|
| Type      | POST |
| Parameters | см https://github.com/nextgis/nextgisweb_compulink/issues/529 |
| Result| VideoInfo |

**Comment by karavanjo** [comment]
Release notes:
* При успешной отработке запроса на создание видео (1), последующий запрос списка файлов должен гарантировано (без задержек) возвращать список, содержащий создаваемое в запросе (1) видео.

**Comment by yellow-sky** [comment]
Готово
