### ISSUE TITLE
Реализовать endpoint для получения статуса записи видео

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#535]
| Параметр| Спецификация|
| ------------- |-------------|
| Name |  `compulink.player.video.get_status` |
| URL      | `/compulink/player/video/status/{id:\d+}` |
| Type      | GET |
| Parameters | - |
| Result| `VideoInfo` |

Описание структуры данных статуса видео (используется структура данных VideoInfo, используемая в https://github.com/nextgis/nextgisweb_compulink/issues/532):
```
// VideoInfo
{
    id: [Number],
    name: [String],
    status: [String('creating', 'ready')]
}
```

**Comment by yellow-sky** [comment]
Работает
