### ISSUE TITLE
Реализовать таймер обновления списка видео при отправке на запись

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#536]
При клике на кнопке "Записать" клиент вызывает оконечную точку `compulink.player.video.crud` с запросом типа `POST`. После этого, кнопка "Записать" блокируется. Оконечная точка возвращает 200 ОК и идентификатор создаваемого видео. Клиент должен отправлять запросы на оконечную точку `compulink.player.video.get_status` (https://github.com/nextgis/nextgisweb_compulink/issues/535) 1 раз в 5 секунд. При получении статуса `ready` таймер должен быть остановлен, а список видео обновлен.

**Comment by karavanjo** [comment]
Реализовано в https://github.com/nextgis/nextgisweb_compulink/commit/38085d67f3996b21fc4987c5f0fccd6301e2d4cc

**Comment by yellow-sky** [comment]
Работает
