### ISSUE TITLE
Add VideoManager switch into panel of player

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#537]

**Comment by karavanjo** [comment]
Implemented.

Turned on:
![image](https://cloud.githubusercontent.com/assets/669999/22558032/5a551776-e97d-11e6-999a-3a3824fb804e.png)

Turned off:
![image](https://cloud.githubusercontent.com/assets/669999/22558051/6b13b2ca-e97d-11e6-8c4d-63d3eecae876.png)

**Comment by yellow-sky** [comment]
Работает
