### ISSUE TITLE
Положение фото при проигрывании

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#544]
Растащить фото по всем углам, кроме угла с панелью плейера.
Панель плеера можно закрепить или даже свернуть.

**Comment by karavanjo** [comment]
Реализовано. 3 контейнера фото, выбор фото осуществляется с использованием стратегии максимального расстояния от текущего объекта до контейнера с фотографией.
Демонстрация доступна по [ссылке](https://youtu.be/Nww2ySKlYYA).

**Comment by karavanjo** [comment]
Реализована RandomStrategy, установлена по умолчанию для PointerControl.
Демонстрация доступна по [ссылке](https://youtu.be/j1nSyQTxPsk).

**Comment by karavanjo** [comment]
Стратегия `RandomStrategy` переиспользована странице записи видео, адаптирована под 4 фотографии. На странице плеера используется 3 фото. Демонстрация доступна по [ссылке](https://www.youtube.com/watch?v=taMJ3xO41Y4).

**Comment by yellow-sky** [comment]
Работает
