### ISSUE TITLE
Оформление принятых участков

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#546]
принятый участок: самый нижний слой, шире самого широкого элемента трассы кабеля, цвет светло зеленый, яркость меняется при выделении участка
принятые и выделенный участки должны быть под всеми остальными слоями

**Comment by karavanjo** [comment]
Порядок снизу вверх:
1. принятый участок - шире самого широкого элемента трассы кабеля (Спецпереход), цвет светло-зеленый
2. выделенный принятый участок  - шире, чем '1', цвет зеленый.

Цвета ВОЛС - https://github.com/nextgis/nextgisweb_compulink/issues/547

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/22481305/ce7094ec-e805-11e6-9fe1-7d60739d8815.png)

**Comment by yellow-sky** [comment]
Если не считать ошибки #541, то все ок.
