### ISSUE TITLE
«Нет принятых участков» заезжает на шапку таблицы

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#552]
Если текст заголовка таблицы «Принятые участки» отображается в две строки, то надпись «Нет принятых участков» заезжает на шапку таблицы
![image](https://cloud.githubusercontent.com/assets/1277422/22448636/e58eef56-e76b-11e6-8061-322703f49d4f.png)

**Comment by karavanjo** [comment]
Исправлено.
Демо доступно по [ссылке](https://youtu.be/FNSxL7pEi-Q).

:bulb: Tested on `IE 11.576, Windows 10 Home`
:bulb: Tested on `Mozilla Firefox 44.0, Windows 10 Home`
:bulb: Tested on `Chromium Version 48.0.2564.82 Ubuntu 15.04 (64-bit)`
:bulb: Tested on `Chrome Version 57.0.2987.110 Windows 10 Home (64-bit)`
