### ISSUE TITLE
Переместить столбцы «Дата изменений» и «Автор изменений»

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#555]
В таблице «Принятые участки»: Столбцы «Дата изменений» и «Автор изменений» должны быть последними столбцами в таблице

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/23064250/05981608-f520-11e6-982e-115fb53db6c5.png)

**Comment by yellow-sky** [comment]
Работает
