### ISSUE TITLE
Wrong position of photo in recorded video file

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#561]
![image](https://cloud.githubusercontent.com/assets/669999/22550757/9b622d00-e962-11e6-9940-8faa8af8c392.png)

**Comment by karavanjo** [comment]
Fixed.
![image](https://cloud.githubusercontent.com/assets/669999/22551278/3853dc1a-e965-11e6-8169-ff9476305eac.png)

**Comment by yellow-sky** [comment]
Работает
