### ISSUE TITLE
Added 'error' status for creating video process

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#562]
`get_video_status` route should return status `error` if raised an error on server side

**Comment by yellow-sky** [comment]
Работает

**Comment by karavanjo** [comment]
Цвет строки с названием файла при ошибке также установлен в "красный":
![image](https://cloud.githubusercontent.com/assets/669999/22857254/cbf35f50-f0b2-11e6-8f7b-fbd5abdd49f4.png)

**Comment by yellow-sky** [comment]
Работает
