### ISSUE TITLE
Панель видео. Плывет верстка в Firefox

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#565]
![image](https://cloud.githubusercontent.com/assets/1277422/22736753/d6be3364-ee10-11e6-9170-fa27c063af41.png)

**Comment by karavanjo** [comment]
Исправлено, протестировано в:
* Firefox, 44.0, Ubuntu 15.04 (64-bit)
![image](https://cloud.githubusercontent.com/assets/669999/23061897/a858d244-f514-11e6-905e-4ae145f69a71.png)

* Chromium, 48.0.2564.82 Ubuntu 15.04 (64-bit)
![image](https://cloud.githubusercontent.com/assets/669999/23061905/b15a1a56-f514-11e6-9c84-d81ffc28233c.png)

**Comment by yellow-sky** [comment]
Работает
