### ISSUE TITLE
При ошибке вызова make_video кнопка перманентно блокируется

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#566]
Отображается окно с ошибкой (что хорошо), но кнопка так и остается заблокированной. Повторить попытку пользователь уже не может.

![image](https://cloud.githubusercontent.com/assets/1277422/22737545/a076d60e-ee14-11e6-9020-425a3e8a86c4.png)

**Comment by karavanjo** [comment]
Исправлено:
![566](https://cloud.githubusercontent.com/assets/669999/23061000/1f154510-f511-11e6-8a7f-e55420521ab9.gif)

**Comment by yellow-sky** [comment]
Работает
