### ISSUE TITLE
Перевернуть список видео

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#567]
Сейчас список видео отображается от старых к новым. Нужно перевернуть список, так как новый не виден при добавлении.

**Comment by karavanjo** [comment]
Сортировать по VideoInfoDetail.created_date_time (https://github.com/nextgis/nextgisweb_compulink/issues/532)

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/23060544/3aefe260-f50f-11e6-90d8-3c9a3ed55f6c.png)

**Comment by yellow-sky** [comment]
Работает
