### ISSUE TITLE
Выделить создаваемые видео

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#569]
нужно как то отделить записанные видео от создаваемого
индикатор записи - статичный, не наглядный

**Comment by yellow-sky** [comment]
возможно что их нужно отображать в начале списка

**Comment by karavanjo** [comment]
Добавить динамичный индикатор в виде .gif иконки.

**Comment by karavanjo** [comment]
Индикатор добавлен:
![569](https://cloud.githubusercontent.com/assets/669999/23059822/16ea9a20-f50c-11e6-9bbd-b9e3b088b623.gif)

**Comment by yellow-sky** [comment]
Работает
