### ISSUE TITLE
Синхронизировать линию и фото

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#570]
на видео - сначала появляется соединительная линия, потом фото - надо одновременно

**Comment by yellow-sky** [comment]
нужно попытаться это сделать - если не выйдет - отписаться по причинам

**Comment by karavanjo** [comment]
Эффекты появления / исчезновения фотографии и линии указатели синхронизированы. Демо доступно [здесь](https://youtu.be/cFEVXQVyv9Y).

**Comment by yellow-sky** [comment]
Работает
