### ISSUE TITLE
Фото в разных углах 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#571]
два фото подряд могут в одном углу показываться - нужно чтобы каждая новая фото отображалась в новом углу (и при обычном проигрывании та же беда)

**Comment by yellow-sky** [comment]
Работает

**Comment by yellow-sky** [comment]
У заказчика произошел рецидив:
замечание: опять несколько раз было две фото подряд в одном углу

**Comment by karavanjo** [comment]
Исправлено, готово к тестированию.

**Comment by yellow-sky** [comment]
Работает
