### ISSUE TITLE
Значок (+) заменить на более ясный

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#572]
- значок (+) заменить на что то из этого:
![image](https://cloud.githubusercontent.com/assets/1277422/22782494/69411ebe-eed8-11e6-82e7-a376444c20c6.png)

**Comment by karavanjo** [comment]
Вариант:
![image](https://cloud.githubusercontent.com/assets/669999/22857195/82289b98-f0b1-11e6-94ec-02470bf1bd56.png)

**Comment by yellow-sky** [comment]
Работает
