### ISSUE TITLE
Отключить наезд при включении слоев с принятыми участками

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#578]
замечание: просматривая конкретный принятый участок на большом приближении, выключить и сразу  включить слой принятых участков - отрабатывает масштабирование, которое показывают всю трассу!
масштаб менять не нужно при вкл/откл слоя принятых участков

**Comment by karavanjo** [comment]
Реализовано.

**Comment by yellow-sky** [comment]
Работает
