### ISSUE TITLE
Не отображается окно с записанным видео

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#581]
Нашел такую штуку:
1) Открыть окно с видео
2) Изменить размер окна (свернуть например, или просто сделать меньше)
3) Включить окно записанных видео

Окно на видно, оно находится в координатах за границами окна.

**Comment by karavanjo** [comment]
Исправлено - после включения окно будет располагаться в нижнем правом углу страницы.

**Comment by yellow-sky** [comment]
Работает
