### ISSUE TITLE
В Firefox не отображается панель видео

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#587]

**Comment by karavanjo** [comment]
Исправлено:


![image](https://cloud.githubusercontent.com/assets/669999/23604658/a9b09894-026a-11e7-88c0-e74c1fceae97.png)
:bulb: Tested on `Mozilla Firefox 44.0, Ubuntu 15.04`

**Comment by yellow-sky** [comment]
Работает
