### ISSUE TITLE
Принятые участки - адаптировать UI под различные права пользователей

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#591]
Возможность добавлять новые и редактировать существующие принятые участки должны быть разграничены новыми правами пользователя — «Объект строительства: Редактирование принятых участков». Возможность просмотра принятых участков должна быть только у пользователей, которым назначено право «Объект строительства: Просмотр принятых участков»

**Comment by karavanjo** [comment]
Реализовано. Спецификация структуры данных о правах приведена в https://github.com/nextgis/nextgisweb_compulink/issues/590

1. disable - все элементы управления отключены, выводится надпись:
![image](https://cloud.githubusercontent.com/assets/669999/23901661/4bba3f9a-08cf-11e7-89ca-02b1aeb6040c.png)
2. list - контекстное меню отключено, выключены инструменты создания принятого участка
![image](https://cloud.githubusercontent.com/assets/669999/23901725/8780d494-08cf-11e7-9766-0fda5d2d97f3.png)
3. edit - активны все элементы управления и контекстное меню:
![image](https://cloud.githubusercontent.com/assets/669999/23901698/72e63dc6-08cf-11e7-809b-822613b10c33.png)

**Comment by yellow-sky** [comment]
Работает
