### ISSUE TITLE
Запретить редактирование участка линии связи с принятым участком

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#592]
После ввода нового принятого участка, редактирование соответствующего участка линии связи должна быть запрещено. на всем протяжении принятого участка: точки не должны перемещаться, принятый участок должен быть не удаляем

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/24188551/cee392ee-0ef2-11e7-9ca2-d5f1c823c4da.png)
1. Нередактируемые геометрии отображаются серым цветом в соответствии со [стилем](https://github.com/nextgis/nextgisweb_compulink/blob/c6028046340c99651a3bd28fd8e58af78ebc5ad1/nextgisweb_compulink/compulink_editor/amd/ngw-compulink-editor/editor/FeaturesManager.js#L47-L47).
2. Нередактируемые геометрии не попадают в контекстное меню и не выбираются для редактирования.

**Comment by yellow-sky** [comment]
Работает
