### ISSUE TITLE
Не отображать первое фото при открытии проигрывания хода строительства

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#593]
При открытии хода проигрывания не следует отображать сразу первое фото (и соединительную линию) - показ начинать только при нажатии на PLAY

**Comment by karavanjo** [comment]
Сценарий использования:
1. При начальной загрузке плеера - фото скрыто, элемент управления "Фото" в состоянии включен - ![image](https://cloud.githubusercontent.com/assets/669999/23704228/e7536e82-0414-11e7-9ff0-b031767f4110.png)
1а. При нажатии кнопки воспроизведение фото появляется.
1b. При перемещении линии времени фото появляется.
2. При начальной загрузке плеера - при отключении элемента управления "Фото" и его повторном включении - фото появляется.
3. При начальной загрузке плеера - при нажатии любого активного элемента управления временем на панели воспроизведения - ![image](https://cloud.githubusercontent.com/assets/669999/23704340/737bd764-0415-11e7-9525-a51ce7211f9d.png) - фото появляется.

Требуется утвердить логику сценария использования либо внести коррективы.

**Comment by karavanjo** [comment]
Уточнено после обсуждения:

Сценарий использования:
1. При начальной загрузке плеера - фото скрыто, элемент управления "Фото" в состоянии включен - ![image](https://cloud.githubusercontent.com/assets/669999/23704228/e7536e82-0414-11e7-9ff0-b031767f4110.png)
1а. При нажатии кнопки воспроизведение **фото появляется**.
1b. При перемещении линии времени **фото появляется**.
2. При начальной загрузке плеера - при отключении элемента управления "Фото" и его повторном включении - **фото не появляется**.
3. При начальной загрузке плеера - при нажатии "Переместить в конец"на панели воспроизведения - ![image](https://cloud.githubusercontent.com/assets/669999/23704340/737bd764-0415-11e7-9525-a51ce7211f9d.png) - **фото появляется**. При нажатии на "Стоп" в состоянии начальной загрузки плеера - **фото не появляется**.

**Comment by karavanjo** [comment]
Реализовано.

**Comment by yellow-sky** [comment]
Работает
