### ISSUE TITLE
Не исчезает Standby загрузки плеера

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#594]
![image](https://cloud.githubusercontent.com/assets/669999/23738723/c5193792-04ab-11e7-8b9c-d10eac976bab.png)

**Comment by yellow-sky** [comment]
Работает

**Comment by karavanjo** [comment]
Прблема в том, что после реализации таска https://github.com/nextgis/nextgisweb_compulink/issues/550 библиотека `Howl` не может загрузить аудио-файл без расширения. Требуется изменить оконечную точку для возврата файла с расширением, таск https://github.com/nextgis/nextgisweb_compulink/issues/595.
Необходимо разработать механизм обработки ошибок при загрузке аудио файла, таск https://github.com/nextgis/nextgisweb_compulink/issues/596
