### ISSUE TITLE
Даты в панели принятых участков - привести к виду DD.MM.YYYY

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#597]

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/23745852/dab0afbc-04ca-11e7-87d4-b4fa21dae64f.png)

**Comment by yellow-sky** [comment]
формат неверный - на месяц должно быть две цифры, как и на дату

**Comment by karavanjo** [comment]
Исправлено:
![image](https://cloud.githubusercontent.com/assets/669999/23902083/e10a39a0-08d0-11e7-991f-1e44fd893703.png)

**Comment by yellow-sky** [comment]
Работает
