### ISSUE TITLE
Пропадают точки при вводе

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#598]
После отметки нового принятого участка появляется окно для ввода атрибутов участка. Почему при этом скрываются маркеры выделенного участка? Маркеры не должны скрываться, чтобы пользователь видел атрибуты какого участка он вносит.

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/24043562/39e0a808-0b28-11e7-97b9-7552b5ddbfad.png)

**Comment by yellow-sky** [comment]
Работает
