### ISSUE TITLE
Включение\выключение принятых участков

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#605]
включаем отображение принятых участков -> отключаем все ОС -> включаем ОС и выделчем его -> кнопка "+" недоступна (становится доступной после откл. и повторного вкл. принятых участков)

**Comment by yellow-sky** [comment]
Вроде уже было?

**Comment by karavanjo** [comment]
Исправлено.

**Comment by yellow-sky** [comment]
Работает
