### ISSUE TITLE
Блокировать меню браузера

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#608]
Связано с реализацией https://github.com/nextgis/nextgisweb_compulink/issues/591
Если у пользователя права только на просмотр, то правый щелчок мыши вызывает меню браузера вместо меню действий - лучше вообще блокировать вывод меню, или выводить меню с надписью "нет доступных действий"

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/23948455/1769616a-0994-11e7-92f2-0b13b11bc0e9.png)

**Comment by yellow-sky** [comment]
Работиет
