### ISSUE TITLE
Притягивание точек создаваемого принятого участка к любому объекту Фактических слоев

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#609]
Возможно ли сделать притягивание к любому объекту Фактического слоя?

**Comment by karavanjo** [comment]
Принято решение установить "прилипание" для точек слоя ActualRealOpticalCableLayer, т.к. вершины линий являются точечными объектами Фактических слоев. Значение `OPTICAL_CABLE_LAYER_POINTS_TOLERANCE` должно быть установлено в `30 пикс`.

**Comment by karavanjo** [comment]
Реализовано.

**Comment by yellow-sky** [comment]
Работает
