### ISSUE TITLE
Перенос кнопки "вкл/откл слоя"

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#610]
Кнопку "вкл/откл слоя" переносим в место перед кнопкой "+" и отделяем её от прочих разделителем (вертикальной чертой)

**Comment by karavanjo** [comment]
Реализовано:
![image](https://cloud.githubusercontent.com/assets/669999/23999084/4dd08902-0a68-11e7-8757-4333ddd46aad.png)

**Comment by yellow-sky** [comment]
Работает
