### ISSUE TITLE
Сбрасывается состояние элементов управления панели принятых участков

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#611]
> Кнопка "вкл/откл" слоя должна быть всегда доступна для включения/отключения и не должна менять своё состояние при любых действиях пользователя, включая удаление принятого участка

При редактировании, удалении или создании принятого участка состояние элементов панели принятых участков сбрасывается к первоначальному - кнопка "вкл/откл" слоя выключена, панель поиска очищена, кнопка создания не нажата. Состояние панели при данных операциях должно оставаться в последнем варианте выбора.

**Comment by karavanjo** [comment]
Исправлено: состояние панели при редактировании, удалении или создании принятого участка остается в последнем варианте выбора.

**Comment by yellow-sky** [comment]
Работает.
