### ISSUE TITLE
Неясное состояние при отмене ввода участка

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#612]
Ккнопки "+", "Отменить точку" и "отображение списка принятых участков" активируем только при выборе/отметке ОС; при отключении в дереве отмеченного ОС - откатывать процесс ввода участка (сейчас курсор с точкой так и мается по карте)

**Comment by karavanjo** [comment]
Реализовано: при выборе нового ОС в таблице выбранных ОС либо при выборе нового ОС в дереве ОС `AcceptedPartsCreator` деактивируется.

**Comment by yellow-sky** [comment]
Работает
