### ISSUE TITLE
Ошибка при вводе участка (пункт е)

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#613]
Начинаю ввод нового участка. Зажимаю левую кнопку мыши при вводе начальной точки в произвольном месте и тащу карту на любое расстояние -> отпускаю кнопку -> открывается окно для ввода атрибутов участка

**Comment by karavanjo** [comment]
Исправлено.

**Comment by yellow-sky** [comment]
Работает
