### ISSUE TITLE
Не учитывается подложка при записи видео

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#614]

**Comment by yellow-sky** [comment]
@karavanjo поправь https://github.com/nextgis/nextgisweb_compulink/blob/fb35a76cd2d9b52a645f4384e89db3aef0137e20/nextgisweb_compulink/compulink_video_producer/view.py#L93 когда добавишь передачу параметра

**Comment by karavanjo** [comment]
Реализовано.

**Comment by yellow-sky** [comment]
Гугло ошибка

**Comment by yellow-sky** [comment]
Решено
