### ISSUE TITLE
Изменение панели записанного видео

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#616]
1. От доп.окна отказываемся

2. на плейере 2 кнопки и инфо-область для сообщений (слева направо):
- красная кнопка «Сформировать видео-файл»
- инфо-панель для сообщений
- синяя кнопка «Скачать видео-файл»

3. Примерный внешний вид и поведение таково:
![image](https://cloud.githubusercontent.com/assets/1277422/23996599/e1639e0c-0a45-11e7-9eda-9e3209711822.png)

![image](https://cloud.githubusercontent.com/assets/1277422/23996602/e5e37858-0a45-11e7-973c-e6d9703ea7f2.png)

4. Если файл уже сформирован и пользователь наживает красную кнопку - выдавать сообщение «Файл уже сформирован. Перезаписать или скачать существующий: [Перезаписать] [Скачать]»

5. Во время состояния 2 блокировать кнопку записи

6.  В состоянии 3 изменить надпись на: 
Файл сформирован.
Дата: [дата]   Размер: [размер]
Для скачивания нажмите кнопку справа.

**Comment by yellow-sky** [comment]
Рамочку вокруг Скачать видео делать не нужно. Она только для выделения области на макете.

**Comment by karavanjo** [comment]
В случае возникновения ошибки при записи:
1. Запуск записи.
2. Ожидание записи.
3. Сообщение об ошибке в диалоговом окне.
4. Сброс секции видео в состояние готовности к записи (`1`).

**Comment by karavanjo** [comment]
Реализовано.
1. Режим инициализации видео - необходим для загрузки текущего статуса:
![image](https://cloud.githubusercontent.com/assets/669999/24080935/262c5f8a-0cba-11e7-91f1-5ff219254ebf.png)
2. Режим "Файл сформирован":
![image](https://cloud.githubusercontent.com/assets/669999/24080942/3e84aede-0cba-11e7-86c8-cc6751c09c5c.png)
3. Режим "Ошибка при записи файла":
![image](https://cloud.githubusercontent.com/assets/669999/24080953/4fbc388e-0cba-11e7-9850-1da833bed5df.png)
4. Режим "Формирование файла":
![image](https://cloud.githubusercontent.com/assets/669999/24080959/64cb0660-0cba-11e7-979c-e3b1cfa05b92.png)
5. Диалоговое окно о перезаписи существующего файла:
![image](https://cloud.githubusercontent.com/assets/669999/24080970/8cb87d88-0cba-11e7-874a-590e971ede9b.png)

:bulb: Tested on `IE 11.576, Windows 10 Home`, [demo](https://youtu.be/D_EyOPiln6s)
:bulb: Tested on `Mozilla Firefox 44.0, Ubuntu 15.04`
:bulb: Tested on `Chromium Version 48.0.2564.82 Ubuntu 15.04 (64-bit)`

**Comment by karavanjo** [comment]
Добавить поддержку статуса `none`:
![image](https://cloud.githubusercontent.com/assets/669999/24105121/ffd41860-0d94-11e7-9646-309ee61025b3.png)

**Comment by karavanjo** [comment]
Добавлена поддержку статуса `none`:
![image](https://cloud.githubusercontent.com/assets/669999/24110987/0fb9130a-0da6-11e7-803b-2bf409a82562.png)

**Comment by yellow-sky** [comment]
Работает
