### ISSUE TITLE
Принятые участки - ошибка верификации второй точки

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#617]
Ожидается - вторую точку нельзя поставить на линию принятого участка
Имеем - вторая точка ставиться на существующую линию принятого участка

**Comment by karavanjo** [comment]
Исправлено.

**Comment by karavanjo** [comment]
На точке в принятых участках - верификация некорректна, на линиях - все нормально.

**Comment by karavanjo** [comment]
Исправлено.

**Comment by yellow-sky** [comment]
Работает!
