### ISSUE TITLE
Изменить поведение оконечной точки для видео

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#618]
Необходимо для реализации https://github.com/nextgis/nextgisweb_compulink/issues/616

1. Оконечная точка с маршрутом `compulink.player.video.get_status` и адресом `/compulink/player/video/status/{id:\d+}` должна принимать в качестве параметра идентификатор объекта строительства. Когда видео создано, должен возвращаться объект `VideoInfoDeatil` (см. https://github.com/nextgis/nextgisweb_compulink/issues/532), если видео создается - `VideoInfo` (см. https://github.com/nextgis/nextgisweb_compulink/issues/532).
2. Оконечная точка с маршрутом `compulink.player.video.crud` и адресом `/compulink/player/video` при отправке запроса на создание видео методом `POST` должна принимать параметры записываемого видео, при этом при наличии файла видео - удалить его и запустить создание нового.

**Comment by yellow-sky** [comment]
Работает
