### ISSUE TITLE
Не меняется подсказка при отмене ввода

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#619]
Ставлю первую точку -> Нажимаю кнопку Отмена ввода

Ожидаю:  подсказка == 'Введите первую точку'

Подлучаю:  подсказка == 'Введите конечную точку', но при этом происходит ввод начальной.

**Comment by karavanjo** [comment]
Исправлено.

**Comment by yellow-sky** [comment]
Работает
