### ISSUE TITLE
Кнопка "вкл/откл" слоя

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#632]
кнопка "вкл/откл" слоя должна быть всегда доступна для включения/отключения и не должна менять своё состояние при любых действиях пользователя, включая удаление принятого участка. Воспринимайте эту кнопку как филиал чекбокса из панели "Слои ВОЛС".

**Comment by karavanjo** [comment]
Реализовано.

**Comment by yellow-sky** [comment]
Работает
