### ISSUE TITLE
Переименовать подсказки

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#633]
Высплывающую подсказку для кнопки включения слоя "Принятые участки" изменить на "Вкл / откл отображение принятых участков на карте"

Переименовать пункт контекстного меню строки принятого участка из "Редактировать атрибуты" в "Открыть карточку принятого участка"

**Comment by karavanjo** [comment]
Реализовано:
![633](https://cloud.githubusercontent.com/assets/669999/24664331/08570248-1963-11e7-9511-2272ddac6eb4.gif)

**Comment by yellow-sky** [comment]
Работает
