### ISSUE TITLE
Нет подтяжки к объектам на линии

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#634]
Похоже баг.
Проверить на объектах и тут:

- NEW! курсор притягивается только к "трассе оптического кабеля" и к концам "принятого участка"; остальные объекты фактического слоя не притягивают к себе точку. например на Листе 6 пример: со стороны пустоты расстояние срабатывания действует, а со стороны трассы - нет (курсор свободно скользит до самой точки окончания трассы). А согласно текущему состоянию п.2.4.1 - в момент клика должна быть проверка попадания (пункт ф.)

**Comment by karavanjo** [comment]
Баг не подтвержден, либо требует уточнения - демонстрация snapping новой точки принятого участка к существующим объектам на линии [здесь](https://youtu.be/qrQ9bFZ-rN4). Для линий установлено меньшее значение, чем для точек - этим и достигается необходимый эффект.

**Comment by yellow-sky** [comment]
Баг проявляется на оконечных точках. На серединных все ок

**Comment by karavanjo** [comment]
Реализовано - добавлен snapping к точкам на концах линии оптического кабеля.

**Comment by yellow-sky** [comment]
Работает
