### ISSUE TITLE
Кнопки "В начало", "В конец", "Проиграть", "Остановить" 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#635]
Описание в письме

**Comment by karavanjo** [comment]
Новая логика реализована, демонстрация по [ссылке](https://youtu.be/7w4JqSTxiJU).

![image](https://cloud.githubusercontent.com/assets/669999/24712447/8dcd6cb4-1a2b-11e7-9442-1acfad08727c.png)

**Comment by yellow-sky** [comment]
Работает
