### ISSUE TITLE
Поменять текст

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#636]
текст сообщения при записи первого файла изменить на : "Записать новый видео-файл с текущими параметрами проигрывания? По окончании записи видео-файл станет доступным для скачивания." На плейере изменить  текст "Нажмите кнопку для формирования файла" на "Нажмите кнопку для формирования видео-файла"

**Comment by karavanjo** [comment]
Изменено:
![image](https://cloud.githubusercontent.com/assets/669999/24663561/ef0b2532-1960-11e7-9b7e-86ef79018a7b.png)
![image](https://cloud.githubusercontent.com/assets/669999/24663575/f4c329c0-1960-11e7-85f5-44f6e2aad821.png)

**Comment by yellow-sky** [comment]
Работает
