### ISSUE TITLE
При запуске формирования файла расчитывать длительность

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb_compulink#641]
- если длительность больше или равна отсечке - запрещать формировать файл
- если длительность меньше отсечки, но больше или равна 5 минут - выдавать предупреждение
- иначе просто формировать файл

**Comment by karavanjo** [comment]
Реализовано:
![641](https://cloud.githubusercontent.com/assets/669999/25091407/a22d266c-2391-11e7-896d-164181974b58.gif)

**Comment by yellow-sky** [comment]
Работает
