### ISSUE TITLE
Загрузка документов в форме принятых участков

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#643]
Предлагаю сделать просто - грузить всегда, даже если объект не создается

**Comment by karavanjo** [comment]
Реализовано.

![643](https://cloud.githubusercontent.com/assets/669999/25139005/b6f7628c-2464-11e7-91c3-63f439ad747b.gif)

**Comment by yellow-sky** [comment]
Работает
