### ISSUE TITLE
Переименовать сообщения

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#644]
- Вместо сообщения «Выбрана слишком большая продолжительность проигрывания.» предлагаю следующее «Продолжительность результирующего видео будет больше …. Увеличьте скорость проигрывания перед формированием файла»
- Вместо сообщения «Длительность проигрывания больше 5 минут! Запись файла может занять продолжительное время» предлагаю «Продолжительность результирующего видео будет около … Формирование файла может занять продолжительное время».

**Comment by karavanjo** [comment]
Реализовано:
![644](https://cloud.githubusercontent.com/assets/669999/25188618/5c207b16-252f-11e7-8d5d-ba873c53c40b.gif)

**Comment by karavanjo** [comment]
Реализовано, сообщения изменены:
![644](https://cloud.githubusercontent.com/assets/669999/25278457/a62fdff8-26ab-11e7-960e-33ee7db8d3fb.gif)

**Comment by yellow-sky** [comment]
работает
