### ISSUE TITLE
Вернулся баг с панелью легенды

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#645]
1)      Открыть https://gis.compulink.ru/compulink/monitoring_map

2)      В левом фрейме выбрать любой проект с участками:
![image](https://cloud.githubusercontent.com/assets/1277422/25181646/dfa95db4-251a-11e7-84ad-687ffd578f44.png)

3)      Щёлкнуть на кнопку, отключая легенду и снова нажать на эту кнопку включая легенду:
![image](https://cloud.githubusercontent.com/assets/1277422/25181673/f1a1c4a2-251a-11e7-9548-14b16299d6c7.png)

после двух нажатий так:
![image](https://cloud.githubusercontent.com/assets/1277422/25181686/fac4dff6-251a-11e7-9476-c40f20fac11b.png)

**Comment by karavanjo** [comment]
Исправлено.
![645](https://cloud.githubusercontent.com/assets/669999/25276211/b1df130a-26a1-11e7-913e-423380d68d78.gif)

**Comment by yellow-sky** [comment]
работает
