### ISSUE TITLE
Регрессия: Не работает принятие участка

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#647]
![image](https://cloud.githubusercontent.com/assets/1277422/25181868/98f4eb94-251b-11e7-85de-92f7f36018a5.png)
после нажатия на ОК: участок не появляется, режим ввода нового участка не отключается:
![image](https://cloud.githubusercontent.com/assets/1277422/25181821/7213d47c-251b-11e7-8d92-ec370026a3e2.png)

**Comment by karavanjo** [comment]
Необходимы данные для тестирования - на тестируемом ОС работает.
Выключение кнопки создания нового ПУ после создания ПУ реализовано.
![647](https://cloud.githubusercontent.com/assets/669999/25279753/29d46474-26b0-11e7-9d13-e110a37d56f2.gif)

**Comment by yellow-sky** [comment]
Работает
