### ISSUE TITLE
Убрать надпись

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#649]
При щелчке на ОС при включенном слое «Принятые участки» в панели принятых участков на долю секунды мелькает надпись «Выберите объект строительства»:
![image](https://cloud.githubusercontent.com/assets/1277422/25385197/e90a586c-29cb-11e7-91fa-e3e578202312.png)
Выглядит странно - нужно убрать вывод лишней надписи.

**Comment by karavanjo** [comment]
Добавлено сообщение "Загрузка данных..." на время загрузки данных между переключениями:
![649](https://cloud.githubusercontent.com/assets/669999/25438869/63e94a52-2aa3-11e7-8fb6-c899a0c56163.gif)

Думаю, такое решение более оптимально в сравнении с решением, когда после клика некоторое время ничего не происходит, а затем появляются данные.

**Comment by yellow-sky** [comment]
работает
