### ISSUE TITLE
Стиль трассы ОК в режиме проигрывания

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#654]
отображать линию трассы ОК из слоя «Трасса оптического кабеля (факт)» потолще и поярче

**Comment by karavanjo** [comment]
Варианты:
1. Сейчас (3px, `#9C7900`):
![image](https://cloud.githubusercontent.com/assets/669999/25650123/658dc7ee-2fe3-11e7-8d1d-8ee63c3ccaad.png)
2. 5px, `#ffa800`
![image](https://cloud.githubusercontent.com/assets/669999/25650133/73c23f2a-2fe3-11e7-89f2-8de2bf04d496.png)
3. 5px, `#ffd200`:
![image](https://cloud.githubusercontent.com/assets/669999/25650213/1697fbcc-2fe4-11e7-9fb7-c7f4b39a7f33.png)

**Comment by yellow-sky** [comment]
давай 2.

**Comment by karavanjo** [comment]
Реализовано.
