### ISSUE TITLE
Добавить тип объекта в окно идентификации

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#70]
Сейчас выводится название (#) объекта и родительский элемент. 
Необходимо указывать тип объекта (название слоя).

**Comment by karavanjo** [comment]
![image](https://cloud.githubusercontent.com/assets/669999/8613955/7fa9a4be-26ed-11e5-9e1d-e27c9170e408.png)
Добавить название слоя в формате НАЗВАНИЕ СЛОЯ: НАЗВАНИЕ ОБЪЕКТА (ТИП РЕСУРСА)

**Comment by yellow-sky** [comment]
Работает

**Comment by yellow-sky** [comment]
Пришли новые вводные :(

Необходимо выводить не наименование слоя, а наименование типа объекта в единственном числе. 
При этом для проектных данных в скобках указывать слово «проект», (например, «Точка доступа (проект)»), а для фактических данных ничего дополнительно не указывать (например, «Оптическая муфта»). Для сокращения наименования объекты в слое «Отметки трассы оптического кабеля (факт)» именовать «Точка трассы ВОЛС», объекты в слое «Трасса оптического кабеля (факт)» именовать «Трасса ВОЛС (факт)»

**Comment by yellow-sky** [comment]
Вопрос, где хранить эти алиасы (

**Comment by yellow-sky** [comment]
Обновили сегодня:
В окне идентификации объекта для объектов слоев «Отметки трассы оптического кабеля (факт)», «Трасса оптического кабеля (факт)» не отображается наименование объекта строительства:
![image](https://cloud.githubusercontent.com/assets/1277422/10312533/5b104db8-6c54-11e5-84bd-9c49b9766d3d.png)

**Comment by karavanjo** [comment]
Реализовано.
![image](https://cloud.githubusercontent.com/assets/669999/10944887/4a1241f8-832c-11e5-8ad9-8dc4994f1593.png)

**Comment by yellow-sky** [comment]
Да, работает.
