### ISSUE TITLE
Окно идентификации появляется под слоями

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#73]
Последние изменения привели к тому, что оно вываливается под слоем. Явно z-index у него меньше чем у слоев.

**Comment by karavanjo** [comment]
Установлено большое значение z-index для попапа:

![image](https://cloud.githubusercontent.com/assets/669999/7046000/873d77c6-de0b-11e4-9ab7-b2e4462450dc.png)

**Comment by yellow-sky** [comment]
Работает
