### ISSUE TITLE
Цвет не включаемых чекбоксов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#74]
У нас есть чекбоксы которые можно включить - районы и все что ниже, и те которые не включаются - более верхнего уровня. они только показывают что что-то включено внутри.
Вид у них один, и это сильно путает. 
Не включаемые необходимо красить в как задизейблинные.

**Comment by karavanjo** [comment]
Изменен цвет иконки на серый, уменьшена прозрачность checkbox и выключено изменение стиля при наведении курсора:
![image](https://cloud.githubusercontent.com/assets/669999/7061466/f20d1a9a-de9a-11e4-8177-5c8643d14bce.png)

**Comment by karavanjo** [comment]
В качестве альтернативы можно изменить цвет подписи:
![image](https://cloud.githubusercontent.com/assets/669999/7061503/95d59008-de9b-11e4-892c-47c2a0fae755.png)

**Comment by yellow-sky** [comment]
При наведении на такой чекбокс пропадает галка

**Comment by yellow-sky** [comment]
Работает
