### ISSUE TITLE
Как сделать индикацию при запросе идентификации 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb_compulink#93]
Сейчас не ясно, ушел запрос или нет. Нашел объект или нет.
Предложение менять иконку у инструмента идентификации на крутящийся кружок.

**Comment by yellow-sky** [comment]
Либо делать крутящийся курсор, но как гарантировать, что при ошибке он вернется в нормальный вид?

**Comment by karavanjo** [comment]
При старте идентификации появляется крутящийся загрузчик с надписью "Идентификация..."
![image](https://cloud.githubusercontent.com/assets/669999/9027270/d887a12c-3957-11e5-9f9d-0ce07cc9b059.png)
Если произойдет ошибка, отработает стандартный обработчик ошибок dojo/xhr. Появится надпись "Ошибка на сервере" и исчезнет через 3 секунды:
![image](https://cloud.githubusercontent.com/assets/669999/9027275/018eeaee-3958-11e5-800e-d5f7ebab2a63.png)
Ошибку можно протестировать отключив VPN, когда карта уже загружена.

**Comment by yellow-sky** [comment]
Работает

**Comment by yellow-sky** [comment]
Индикация должна появляться в месте щелчка курсором. Сделать маленький кружок в том же месте, где и был щелчек. Аналогично тому как это сделано на кадастройвой карте.

**Comment by karavanjo** [comment]
Добавлен маркер идентификации в месте клика на карте.
При клике появляется иконка загрузки в виде динамически увеличивающихся окружностей. Одна окружность темно-синего цвета, вторая - светло-синего. Иконка маркера идентификатора:
![ripple](https://cloud.githubusercontent.com/assets/669999/10268411/629c9aea-6ac0-11e5-838e-2ad3b486b0c5.gif)

Результат:
![image](https://cloud.githubusercontent.com/assets/669999/10268380/a1ed8926-6abf-11e5-8a3b-e8c58e97baf8.png)

Выбор светлого обусловлен тем, что у нас есть черные иконки, на фоне которых темно-синий будет неразличим.
![image](https://cloud.githubusercontent.com/assets/669999/10268392/e9989338-6abf-11e5-989d-89820aa76c89.png)

Также добавлен маркер на точку клика:
![image](https://cloud.githubusercontent.com/assets/669999/10268397/01691a1e-6ac0-11e5-8774-b2328ae5f790.png)

В качестве иконки маркера выбрана стандартная иконка инструмента "Идентификация" NextGIS Web.

**Comment by yellow-sky** [comment]
Работает!
Я думаю в будущем имеет смысл перенести в ядро

**Comment by simgislab** [comment]
да, пожалуйста, перенесите эту красоту в НГВ

**Comment by karavanjo** [comment]
Займусь, как закончу с текущими  задачами.
